// Code generated by ent, DO NOT EDIT.

package goalprogresslog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the goalprogresslog type in the database.
	Label = "goal_progress_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldGoalID holds the string denoting the goal_id field in the database.
	FieldGoalID = "goal_id"
	// FieldEmployeeID holds the string denoting the employee_id field in the database.
	FieldEmployeeID = "employee_id"
	// FieldPreviousValue holds the string denoting the previous_value field in the database.
	FieldPreviousValue = "previous_value"
	// FieldNewValue holds the string denoting the new_value field in the database.
	FieldNewValue = "new_value"
	// EdgeGoal holds the string denoting the goal edge name in mutations.
	EdgeGoal = "goal"
	// Table holds the table name of the goalprogresslog in the database.
	Table = "goal_progress_logs"
	// GoalTable is the table that holds the goal relation/edge.
	GoalTable = "goal_progress_logs"
	// GoalInverseTable is the table name for the Goal entity.
	// It exists in this package in order to avoid circular dependency with the "goal" package.
	GoalInverseTable = "goals"
	// GoalColumn is the table column denoting the goal relation/edge.
	GoalColumn = "goal_id"
)

// Columns holds all SQL columns for goalprogresslog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldGoalID,
	FieldEmployeeID,
	FieldPreviousValue,
	FieldNewValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the GoalProgressLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByGoalID orders the results by the goal_id field.
func ByGoalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoalID, opts...).ToFunc()
}

// ByEmployeeID orders the results by the employee_id field.
func ByEmployeeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmployeeID, opts...).ToFunc()
}

// ByPreviousValue orders the results by the previous_value field.
func ByPreviousValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousValue, opts...).ToFunc()
}

// ByNewValue orders the results by the new_value field.
func ByNewValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewValue, opts...).ToFunc()
}

// ByGoalField orders the results by goal field.
func ByGoalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGoalStep(), sql.OrderByField(field, opts...))
	}
}
func newGoalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GoalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GoalTable, GoalColumn),
	)
}
