// Code generated by ent, DO NOT EDIT.

package globalgoalrule

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the globalgoalrule type in the database.
	Label = "global_goal_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGoalID holds the string denoting the goal_id field in the database.
	FieldGoalID = "goal_id"
	// FieldRuleType holds the string denoting the rule_type field in the database.
	FieldRuleType = "rule_type"
	// FieldDepartmentID holds the string denoting the department_id field in the database.
	FieldDepartmentID = "department_id"
	// FieldMinDirectReports holds the string denoting the min_direct_reports field in the database.
	FieldMinDirectReports = "min_direct_reports"
	// FieldDefaultWeight holds the string denoting the default_weight field in the database.
	FieldDefaultWeight = "default_weight"
	// EdgeGoal holds the string denoting the goal edge name in mutations.
	EdgeGoal = "goal"
	// EdgeDepartment holds the string denoting the department edge name in mutations.
	EdgeDepartment = "department"
	// Table holds the table name of the globalgoalrule in the database.
	Table = "global_goal_rules"
	// GoalTable is the table that holds the goal relation/edge.
	GoalTable = "global_goal_rules"
	// GoalInverseTable is the table name for the Goal entity.
	// It exists in this package in order to avoid circular dependency with the "goal" package.
	GoalInverseTable = "goals"
	// GoalColumn is the table column denoting the goal relation/edge.
	GoalColumn = "goal_id"
	// DepartmentTable is the table that holds the department relation/edge.
	DepartmentTable = "global_goal_rules"
	// DepartmentInverseTable is the table name for the OrgNode entity.
	// It exists in this package in order to avoid circular dependency with the "orgnode" package.
	DepartmentInverseTable = "org_nodes"
	// DepartmentColumn is the table column denoting the department relation/edge.
	DepartmentColumn = "department_id"
)

// Columns holds all SQL columns for globalgoalrule fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGoalID,
	FieldRuleType,
	FieldDepartmentID,
	FieldMinDirectReports,
	FieldDefaultWeight,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultWeightValidator is a validator for the "default_weight" field. It is called by the builders before save.
	DefaultWeightValidator func(float64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// RuleType defines the type for the "rule_type" enum field.
type RuleType string

// RuleType values.
const (
	RuleTypeDepartment       RuleType = "department"
	RuleTypeMinDirectReports RuleType = "min_direct_reports"
)

func (rt RuleType) String() string {
	return string(rt)
}

// RuleTypeValidator is a validator for the "rule_type" field enum values. It is called by the builders before save.
func RuleTypeValidator(rt RuleType) error {
	switch rt {
	case RuleTypeDepartment, RuleTypeMinDirectReports:
		return nil
	default:
		return fmt.Errorf("globalgoalrule: invalid enum value for rule_type field: %q", rt)
	}
}

// OrderOption defines the ordering options for the GlobalGoalRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGoalID orders the results by the goal_id field.
func ByGoalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoalID, opts...).ToFunc()
}

// ByRuleType orders the results by the rule_type field.
func ByRuleType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleType, opts...).ToFunc()
}

// ByDepartmentID orders the results by the department_id field.
func ByDepartmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartmentID, opts...).ToFunc()
}

// ByMinDirectReports orders the results by the min_direct_reports field.
func ByMinDirectReports(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinDirectReports, opts...).ToFunc()
}

// ByDefaultWeight orders the results by the default_weight field.
func ByDefaultWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultWeight, opts...).ToFunc()
}

// ByGoalField orders the results by goal field.
func ByGoalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGoalStep(), sql.OrderByField(field, opts...))
	}
}

// ByDepartmentField orders the results by department field.
func ByDepartmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDepartmentStep(), sql.OrderByField(field, opts...))
	}
}
func newGoalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GoalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GoalTable, GoalColumn),
	)
}
func newDepartmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DepartmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
	)
}
