services:
  web:
    build:
      context: ./web
      args:
        VITE_SHOW_DEV_TOOLBAR: ${VITE_SHOW_DEV_TOOLBAR:-false}
    ports:
      - "${WEB_PORT_HTTP:-8080}:80"
      - "${WEB_PORT:-8088}:443"
    depends_on:
      api:
        condition: service_started

  api:
    build:
      context: ./web
      dockerfile: Dockerfile.api
    volumes:
      - ./data:/data
