// Code generated by ent, DO NOT EDIT.

package goaltemplate

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the goaltemplate type in the database.
	Label = "goal_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldUnit holds the string denoting the unit field in the database.
	FieldUnit = "unit"
	// FieldDirection holds the string denoting the direction field in the database.
	FieldDirection = "direction"
	// FieldTargetValue holds the string denoting the target_value field in the database.
	FieldTargetValue = "target_value"
	// FieldGoalKind holds the string denoting the goal_kind field in the database.
	FieldGoalKind = "goal_kind"
	// FieldIsPublic holds the string denoting the is_public field in the database.
	FieldIsPublic = "is_public"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeKpiLinks holds the string denoting the kpi_links edge name in mutations.
	EdgeKpiLinks = "kpi_links"
	// Table holds the table name of the goaltemplate in the database.
	Table = "goal_templates"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "goal_templates"
	// CreatorInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	CreatorInverseTable = "employees"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "created_by"
	// KpiLinksTable is the table that holds the kpi_links relation/edge.
	KpiLinksTable = "goal_template_kpi_links"
	// KpiLinksInverseTable is the table name for the GoalTemplateKpiLink entity.
	// It exists in this package in order to avoid circular dependency with the "goaltemplatekpilink" package.
	KpiLinksInverseTable = "goal_template_kpi_links"
	// KpiLinksColumn is the table column denoting the kpi_links relation/edge.
	KpiLinksColumn = "template_id"
)

// Columns holds all SQL columns for goaltemplate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldName,
	FieldDescription,
	FieldUnit,
	FieldDirection,
	FieldTargetValue,
	FieldGoalKind,
	FieldIsPublic,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// TargetValueValidator is a validator for the "target_value" field. It is called by the builders before save.
	TargetValueValidator func(float64) error
	// DefaultIsPublic holds the default value on creation for the "is_public" field.
	DefaultIsPublic bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Unit defines the type for the "unit" enum field.
type Unit string

// Unit values.
const (
	UnitPorcentaje Unit = "porcentaje"
	UnitMoneda     Unit = "moneda"
	UnitNumero     Unit = "numero"
)

func (u Unit) String() string {
	return string(u)
}

// UnitValidator is a validator for the "unit" field enum values. It is called by the builders before save.
func UnitValidator(u Unit) error {
	switch u {
	case UnitPorcentaje, UnitMoneda, UnitNumero:
		return nil
	default:
		return fmt.Errorf("goaltemplate: invalid enum value for unit field: %q", u)
	}
}

// Direction defines the type for the "direction" enum field.
type Direction string

// DirectionAscendente is the default value of the Direction enum.
const DefaultDirection = DirectionAscendente

// Direction values.
const (
	DirectionAscendente  Direction = "ascendente"
	DirectionDescendente Direction = "descendente"
)

func (d Direction) String() string {
	return string(d)
}

// DirectionValidator is a validator for the "direction" field enum values. It is called by the builders before save.
func DirectionValidator(d Direction) error {
	switch d {
	case DirectionAscendente, DirectionDescendente:
		return nil
	default:
		return fmt.Errorf("goaltemplate: invalid enum value for direction field: %q", d)
	}
}

// GoalKind defines the type for the "goal_kind" enum field.
type GoalKind string

// GoalKind values.
const (
	GoalKindQualitative  GoalKind = "qualitative"
	GoalKindQuantitative GoalKind = "quantitative"
)

func (gk GoalKind) String() string {
	return string(gk)
}

// GoalKindValidator is a validator for the "goal_kind" field enum values. It is called by the builders before save.
func GoalKindValidator(gk GoalKind) error {
	switch gk {
	case GoalKindQualitative, GoalKindQuantitative:
		return nil
	default:
		return fmt.Errorf("goaltemplate: invalid enum value for goal_kind field: %q", gk)
	}
}

// OrderOption defines the ordering options for the GoalTemplate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByUnit orders the results by the unit field.
func ByUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnit, opts...).ToFunc()
}

// ByDirection orders the results by the direction field.
func ByDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirection, opts...).ToFunc()
}

// ByTargetValue orders the results by the target_value field.
func ByTargetValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetValue, opts...).ToFunc()
}

// ByGoalKind orders the results by the goal_kind field.
func ByGoalKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoalKind, opts...).ToFunc()
}

// ByIsPublic orders the results by the is_public field.
func ByIsPublic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPublic, opts...).ToFunc()
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByKpiLinksCount orders the results by kpi_links count.
func ByKpiLinksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newKpiLinksStep(), opts...)
	}
}

// ByKpiLinks orders the results by kpi_links terms.
func ByKpiLinks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKpiLinksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
func newKpiLinksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KpiLinksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, KpiLinksTable, KpiLinksColumn),
	)
}
