// Code generated by ent, DO NOT EDIT.

package pillar

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the pillar type in the database.
	Label = "pillar"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeCompetencies holds the string denoting the competencies edge name in mutations.
	EdgeCompetencies = "competencies"
	// EdgeScaleCriteria holds the string denoting the scale_criteria edge name in mutations.
	EdgeScaleCriteria = "scale_criteria"
	// Table holds the table name of the pillar in the database.
	Table = "pillars"
	// CompetenciesTable is the table that holds the competencies relation/edge.
	CompetenciesTable = "competencies"
	// CompetenciesInverseTable is the table name for the Competency entity.
	// It exists in this package in order to avoid circular dependency with the "competency" package.
	CompetenciesInverseTable = "competencies"
	// CompetenciesColumn is the table column denoting the competencies relation/edge.
	CompetenciesColumn = "pillar_id"
	// ScaleCriteriaTable is the table that holds the scale_criteria relation/edge.
	ScaleCriteriaTable = "scale_criterions"
	// ScaleCriteriaInverseTable is the table name for the ScaleCriterion entity.
	// It exists in this package in order to avoid circular dependency with the "scalecriterion" package.
	ScaleCriteriaInverseTable = "scale_criterions"
	// ScaleCriteriaColumn is the table column denoting the scale_criteria relation/edge.
	ScaleCriteriaColumn = "pillar_id"
)

// Columns holds all SQL columns for pillar fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldVersion,
	FieldName,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Pillar queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCompetenciesCount orders the results by competencies count.
func ByCompetenciesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCompetenciesStep(), opts...)
	}
}

// ByCompetencies orders the results by competencies terms.
func ByCompetencies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompetenciesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByScaleCriteriaCount orders the results by scale_criteria count.
func ByScaleCriteriaCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newScaleCriteriaStep(), opts...)
	}
}

// ByScaleCriteria orders the results by scale_criteria terms.
func ByScaleCriteria(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScaleCriteriaStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCompetenciesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompetenciesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CompetenciesTable, CompetenciesColumn),
	)
}
func newScaleCriteriaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScaleCriteriaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ScaleCriteriaTable, ScaleCriteriaColumn),
	)
}
