// Code generated by ent, DO NOT EDIT.

package nineboxquadrant

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLTE(FieldID, id))
}

// Quadrant applies equality check predicate on the "quadrant" field. It's identical to QuadrantEQ.
func Quadrant(v int) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldQuadrant, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldDescription, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldColor, v))
}

// ActionRecommendation applies equality check predicate on the "action_recommendation" field. It's identical to ActionRecommendationEQ.
func ActionRecommendation(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldActionRecommendation, v))
}

// QuadrantEQ applies the EQ predicate on the "quadrant" field.
func QuadrantEQ(v int) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldQuadrant, v))
}

// QuadrantNEQ applies the NEQ predicate on the "quadrant" field.
func QuadrantNEQ(v int) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNEQ(FieldQuadrant, v))
}

// QuadrantIn applies the In predicate on the "quadrant" field.
func QuadrantIn(vs ...int) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldIn(FieldQuadrant, vs...))
}

// QuadrantNotIn applies the NotIn predicate on the "quadrant" field.
func QuadrantNotIn(vs ...int) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNotIn(FieldQuadrant, vs...))
}

// QuadrantGT applies the GT predicate on the "quadrant" field.
func QuadrantGT(v int) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGT(FieldQuadrant, v))
}

// QuadrantGTE applies the GTE predicate on the "quadrant" field.
func QuadrantGTE(v int) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGTE(FieldQuadrant, v))
}

// QuadrantLT applies the LT predicate on the "quadrant" field.
func QuadrantLT(v int) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLT(FieldQuadrant, v))
}

// QuadrantLTE applies the LTE predicate on the "quadrant" field.
func QuadrantLTE(v int) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLTE(FieldQuadrant, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldContainsFold(FieldLabel, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldContainsFold(FieldDescription, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldHasSuffix(FieldColor, v))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldContainsFold(FieldColor, v))
}

// ActionRecommendationEQ applies the EQ predicate on the "action_recommendation" field.
func ActionRecommendationEQ(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEQ(FieldActionRecommendation, v))
}

// ActionRecommendationNEQ applies the NEQ predicate on the "action_recommendation" field.
func ActionRecommendationNEQ(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNEQ(FieldActionRecommendation, v))
}

// ActionRecommendationIn applies the In predicate on the "action_recommendation" field.
func ActionRecommendationIn(vs ...string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldIn(FieldActionRecommendation, vs...))
}

// ActionRecommendationNotIn applies the NotIn predicate on the "action_recommendation" field.
func ActionRecommendationNotIn(vs ...string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNotIn(FieldActionRecommendation, vs...))
}

// ActionRecommendationGT applies the GT predicate on the "action_recommendation" field.
func ActionRecommendationGT(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGT(FieldActionRecommendation, v))
}

// ActionRecommendationGTE applies the GTE predicate on the "action_recommendation" field.
func ActionRecommendationGTE(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldGTE(FieldActionRecommendation, v))
}

// ActionRecommendationLT applies the LT predicate on the "action_recommendation" field.
func ActionRecommendationLT(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLT(FieldActionRecommendation, v))
}

// ActionRecommendationLTE applies the LTE predicate on the "action_recommendation" field.
func ActionRecommendationLTE(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldLTE(FieldActionRecommendation, v))
}

// ActionRecommendationContains applies the Contains predicate on the "action_recommendation" field.
func ActionRecommendationContains(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldContains(FieldActionRecommendation, v))
}

// ActionRecommendationHasPrefix applies the HasPrefix predicate on the "action_recommendation" field.
func ActionRecommendationHasPrefix(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldHasPrefix(FieldActionRecommendation, v))
}

// ActionRecommendationHasSuffix applies the HasSuffix predicate on the "action_recommendation" field.
func ActionRecommendationHasSuffix(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldHasSuffix(FieldActionRecommendation, v))
}

// ActionRecommendationIsNil applies the IsNil predicate on the "action_recommendation" field.
func ActionRecommendationIsNil() predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldIsNull(FieldActionRecommendation))
}

// ActionRecommendationNotNil applies the NotNil predicate on the "action_recommendation" field.
func ActionRecommendationNotNil() predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldNotNull(FieldActionRecommendation))
}

// ActionRecommendationEqualFold applies the EqualFold predicate on the "action_recommendation" field.
func ActionRecommendationEqualFold(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldEqualFold(FieldActionRecommendation, v))
}

// ActionRecommendationContainsFold applies the ContainsFold predicate on the "action_recommendation" field.
func ActionRecommendationContainsFold(v string) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.FieldContainsFold(FieldActionRecommendation, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NineBoxQuadrant) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NineBoxQuadrant) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NineBoxQuadrant) predicate.NineBoxQuadrant {
	return predicate.NineBoxQuadrant(sql.NotPredicates(p))
}
