// Code generated by ent, DO NOT EDIT.

package nineboxentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the nineboxentry type in the database.
	Label = "nine_box_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldPerformanceScore holds the string denoting the performance_score field in the database.
	FieldPerformanceScore = "performance_score"
	// FieldPotentialScore holds the string denoting the potential_score field in the database.
	FieldPotentialScore = "potential_score"
	// FieldQuadrant holds the string denoting the quadrant field in the database.
	FieldQuadrant = "quadrant"
	// FieldComments holds the string denoting the comments field in the database.
	FieldComments = "comments"
	// FieldMatrixID holds the string denoting the matrix_id field in the database.
	FieldMatrixID = "matrix_id"
	// FieldEvaluateeID holds the string denoting the evaluatee_id field in the database.
	FieldEvaluateeID = "evaluatee_id"
	// EdgeMatrix holds the string denoting the matrix edge name in mutations.
	EdgeMatrix = "matrix"
	// EdgeEvaluatee holds the string denoting the evaluatee edge name in mutations.
	EdgeEvaluatee = "evaluatee"
	// Table holds the table name of the nineboxentry in the database.
	Table = "nine_box_entries"
	// MatrixTable is the table that holds the matrix relation/edge.
	MatrixTable = "nine_box_entries"
	// MatrixInverseTable is the table name for the NineBoxMatrix entity.
	// It exists in this package in order to avoid circular dependency with the "nineboxmatrix" package.
	MatrixInverseTable = "nine_box_matrixes"
	// MatrixColumn is the table column denoting the matrix relation/edge.
	MatrixColumn = "matrix_id"
	// EvaluateeTable is the table that holds the evaluatee relation/edge.
	EvaluateeTable = "nine_box_entries"
	// EvaluateeInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	EvaluateeInverseTable = "employees"
	// EvaluateeColumn is the table column denoting the evaluatee relation/edge.
	EvaluateeColumn = "evaluatee_id"
)

// Columns holds all SQL columns for nineboxentry fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldVersion,
	FieldPerformanceScore,
	FieldPotentialScore,
	FieldQuadrant,
	FieldComments,
	FieldMatrixID,
	FieldEvaluateeID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int) error
	// PerformanceScoreValidator is a validator for the "performance_score" field. It is called by the builders before save.
	PerformanceScoreValidator func(int) error
	// PotentialScoreValidator is a validator for the "potential_score" field. It is called by the builders before save.
	PotentialScoreValidator func(int) error
	// QuadrantValidator is a validator for the "quadrant" field. It is called by the builders before save.
	QuadrantValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the NineBoxEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByPerformanceScore orders the results by the performance_score field.
func ByPerformanceScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerformanceScore, opts...).ToFunc()
}

// ByPotentialScore orders the results by the potential_score field.
func ByPotentialScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPotentialScore, opts...).ToFunc()
}

// ByQuadrant orders the results by the quadrant field.
func ByQuadrant(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuadrant, opts...).ToFunc()
}

// ByComments orders the results by the comments field.
func ByComments(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComments, opts...).ToFunc()
}

// ByMatrixID orders the results by the matrix_id field.
func ByMatrixID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatrixID, opts...).ToFunc()
}

// ByEvaluateeID orders the results by the evaluatee_id field.
func ByEvaluateeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvaluateeID, opts...).ToFunc()
}

// ByMatrixField orders the results by matrix field.
func ByMatrixField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMatrixStep(), sql.OrderByField(field, opts...))
	}
}

// ByEvaluateeField orders the results by evaluatee field.
func ByEvaluateeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEvaluateeStep(), sql.OrderByField(field, opts...))
	}
}
func newMatrixStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MatrixInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MatrixTable, MatrixColumn),
	)
}
func newEvaluateeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EvaluateeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EvaluateeTable, EvaluateeColumn),
	)
}
