// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/cycle"
	"github.com/sed-evaluacion-desempeno/api/internal/cycleconfig"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// CycleConfigUpdate is the builder for updating CycleConfig entities.
type CycleConfigUpdate struct {
	config
	hooks    []Hook
	mutation *CycleConfigMutation
}

// Where appends a list predicates to the CycleConfigUpdate builder.
func (_u *CycleConfigUpdate) Where(ps ...predicate.CycleConfig) *CycleConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCycleID sets the "cycle_id" field.
func (_u *CycleConfigUpdate) SetCycleID(v uuid.UUID) *CycleConfigUpdate {
	_u.mutation.SetCycleID(v)
	return _u
}

// SetNillableCycleID sets the "cycle_id" field if the given value is not nil.
func (_u *CycleConfigUpdate) SetNillableCycleID(v *uuid.UUID) *CycleConfigUpdate {
	if v != nil {
		_u.SetCycleID(*v)
	}
	return _u
}

// SetGWeight sets the "g_weight" field.
func (_u *CycleConfigUpdate) SetGWeight(v float64) *CycleConfigUpdate {
	_u.mutation.ResetGWeight()
	_u.mutation.SetGWeight(v)
	return _u
}

// SetNillableGWeight sets the "g_weight" field if the given value is not nil.
func (_u *CycleConfigUpdate) SetNillableGWeight(v *float64) *CycleConfigUpdate {
	if v != nil {
		_u.SetGWeight(*v)
	}
	return _u
}

// AddGWeight adds value to the "g_weight" field.
func (_u *CycleConfigUpdate) AddGWeight(v float64) *CycleConfigUpdate {
	_u.mutation.AddGWeight(v)
	return _u
}

// SetPWeight sets the "p_weight" field.
func (_u *CycleConfigUpdate) SetPWeight(v float64) *CycleConfigUpdate {
	_u.mutation.ResetPWeight()
	_u.mutation.SetPWeight(v)
	return _u
}

// SetNillablePWeight sets the "p_weight" field if the given value is not nil.
func (_u *CycleConfigUpdate) SetNillablePWeight(v *float64) *CycleConfigUpdate {
	if v != nil {
		_u.SetPWeight(*v)
	}
	return _u
}

// AddPWeight adds value to the "p_weight" field.
func (_u *CycleConfigUpdate) AddPWeight(v float64) *CycleConfigUpdate {
	_u.mutation.AddPWeight(v)
	return _u
}

// SetCycle sets the "cycle" edge to the Cycle entity.
func (_u *CycleConfigUpdate) SetCycle(v *Cycle) *CycleConfigUpdate {
	return _u.SetCycleID(v.ID)
}

// Mutation returns the CycleConfigMutation object of the builder.
func (_u *CycleConfigUpdate) Mutation() *CycleConfigMutation {
	return _u.mutation
}

// ClearCycle clears the "cycle" edge to the Cycle entity.
func (_u *CycleConfigUpdate) ClearCycle() *CycleConfigUpdate {
	_u.mutation.ClearCycle()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CycleConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CycleConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CycleConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CycleConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CycleConfigUpdate) check() error {
	if v, ok := _u.mutation.GWeight(); ok {
		if err := cycleconfig.GWeightValidator(v); err != nil {
			return &ValidationError{Name: "g_weight", err: fmt.Errorf(`internal: validator failed for field "CycleConfig.g_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PWeight(); ok {
		if err := cycleconfig.PWeightValidator(v); err != nil {
			return &ValidationError{Name: "p_weight", err: fmt.Errorf(`internal: validator failed for field "CycleConfig.p_weight": %w`, err)}
		}
	}
	if _u.mutation.CycleCleared() && len(_u.mutation.CycleIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "CycleConfig.cycle"`)
	}
	return nil
}

func (_u *CycleConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cycleconfig.Table, cycleconfig.Columns, sqlgraph.NewFieldSpec(cycleconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GWeight(); ok {
		_spec.SetField(cycleconfig.FieldGWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGWeight(); ok {
		_spec.AddField(cycleconfig.FieldGWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PWeight(); ok {
		_spec.SetField(cycleconfig.FieldPWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPWeight(); ok {
		_spec.AddField(cycleconfig.FieldPWeight, field.TypeFloat64, value)
	}
	if _u.mutation.CycleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cycleconfig.CycleTable,
			Columns: []string{cycleconfig.CycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cycle.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CycleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cycleconfig.CycleTable,
			Columns: []string{cycleconfig.CycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cycle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cycleconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CycleConfigUpdateOne is the builder for updating a single CycleConfig entity.
type CycleConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CycleConfigMutation
}

// SetCycleID sets the "cycle_id" field.
func (_u *CycleConfigUpdateOne) SetCycleID(v uuid.UUID) *CycleConfigUpdateOne {
	_u.mutation.SetCycleID(v)
	return _u
}

// SetNillableCycleID sets the "cycle_id" field if the given value is not nil.
func (_u *CycleConfigUpdateOne) SetNillableCycleID(v *uuid.UUID) *CycleConfigUpdateOne {
	if v != nil {
		_u.SetCycleID(*v)
	}
	return _u
}

// SetGWeight sets the "g_weight" field.
func (_u *CycleConfigUpdateOne) SetGWeight(v float64) *CycleConfigUpdateOne {
	_u.mutation.ResetGWeight()
	_u.mutation.SetGWeight(v)
	return _u
}

// SetNillableGWeight sets the "g_weight" field if the given value is not nil.
func (_u *CycleConfigUpdateOne) SetNillableGWeight(v *float64) *CycleConfigUpdateOne {
	if v != nil {
		_u.SetGWeight(*v)
	}
	return _u
}

// AddGWeight adds value to the "g_weight" field.
func (_u *CycleConfigUpdateOne) AddGWeight(v float64) *CycleConfigUpdateOne {
	_u.mutation.AddGWeight(v)
	return _u
}

// SetPWeight sets the "p_weight" field.
func (_u *CycleConfigUpdateOne) SetPWeight(v float64) *CycleConfigUpdateOne {
	_u.mutation.ResetPWeight()
	_u.mutation.SetPWeight(v)
	return _u
}

// SetNillablePWeight sets the "p_weight" field if the given value is not nil.
func (_u *CycleConfigUpdateOne) SetNillablePWeight(v *float64) *CycleConfigUpdateOne {
	if v != nil {
		_u.SetPWeight(*v)
	}
	return _u
}

// AddPWeight adds value to the "p_weight" field.
func (_u *CycleConfigUpdateOne) AddPWeight(v float64) *CycleConfigUpdateOne {
	_u.mutation.AddPWeight(v)
	return _u
}

// SetCycle sets the "cycle" edge to the Cycle entity.
func (_u *CycleConfigUpdateOne) SetCycle(v *Cycle) *CycleConfigUpdateOne {
	return _u.SetCycleID(v.ID)
}

// Mutation returns the CycleConfigMutation object of the builder.
func (_u *CycleConfigUpdateOne) Mutation() *CycleConfigMutation {
	return _u.mutation
}

// ClearCycle clears the "cycle" edge to the Cycle entity.
func (_u *CycleConfigUpdateOne) ClearCycle() *CycleConfigUpdateOne {
	_u.mutation.ClearCycle()
	return _u
}

// Where appends a list predicates to the CycleConfigUpdate builder.
func (_u *CycleConfigUpdateOne) Where(ps ...predicate.CycleConfig) *CycleConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CycleConfigUpdateOne) Select(field string, fields ...string) *CycleConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CycleConfig entity.
func (_u *CycleConfigUpdateOne) Save(ctx context.Context) (*CycleConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CycleConfigUpdateOne) SaveX(ctx context.Context) *CycleConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CycleConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CycleConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CycleConfigUpdateOne) check() error {
	if v, ok := _u.mutation.GWeight(); ok {
		if err := cycleconfig.GWeightValidator(v); err != nil {
			return &ValidationError{Name: "g_weight", err: fmt.Errorf(`internal: validator failed for field "CycleConfig.g_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PWeight(); ok {
		if err := cycleconfig.PWeightValidator(v); err != nil {
			return &ValidationError{Name: "p_weight", err: fmt.Errorf(`internal: validator failed for field "CycleConfig.p_weight": %w`, err)}
		}
	}
	if _u.mutation.CycleCleared() && len(_u.mutation.CycleIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "CycleConfig.cycle"`)
	}
	return nil
}

func (_u *CycleConfigUpdateOne) sqlSave(ctx context.Context) (_node *CycleConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cycleconfig.Table, cycleconfig.Columns, sqlgraph.NewFieldSpec(cycleconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`internal: missing "CycleConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cycleconfig.FieldID)
		for _, f := range fields {
			if !cycleconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
			}
			if f != cycleconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GWeight(); ok {
		_spec.SetField(cycleconfig.FieldGWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGWeight(); ok {
		_spec.AddField(cycleconfig.FieldGWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PWeight(); ok {
		_spec.SetField(cycleconfig.FieldPWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPWeight(); ok {
		_spec.AddField(cycleconfig.FieldPWeight, field.TypeFloat64, value)
	}
	if _u.mutation.CycleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cycleconfig.CycleTable,
			Columns: []string{cycleconfig.CycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cycle.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CycleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cycleconfig.CycleTable,
			Columns: []string{cycleconfig.CycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cycle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CycleConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cycleconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
