// Code generated by ent, DO NOT EDIT.

package internal

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/cycle"
	"github.com/sed-evaluacion-desempeno/api/internal/cycleconfig"
)

// CycleConfig is the model entity for the CycleConfig schema.
type CycleConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CycleID holds the value of the "cycle_id" field.
	CycleID uuid.UUID `json:"cycle_id,omitempty"`
	// GWeight holds the value of the "g_weight" field.
	GWeight float64 `json:"g_weight,omitempty"`
	// PWeight holds the value of the "p_weight" field.
	PWeight float64 `json:"p_weight,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CycleConfigQuery when eager-loading is set.
	Edges        CycleConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CycleConfigEdges holds the relations/edges for other nodes in the graph.
type CycleConfigEdges struct {
	// Cycle holds the value of the cycle edge.
	Cycle *Cycle `json:"cycle,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CycleOrErr returns the Cycle value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CycleConfigEdges) CycleOrErr() (*Cycle, error) {
	if e.Cycle != nil {
		return e.Cycle, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: cycle.Label}
	}
	return nil, &NotLoadedError{edge: "cycle"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CycleConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cycleconfig.FieldGWeight, cycleconfig.FieldPWeight:
			values[i] = new(sql.NullFloat64)
		case cycleconfig.FieldID, cycleconfig.FieldCycleID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CycleConfig fields.
func (_m *CycleConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cycleconfig.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case cycleconfig.FieldCycleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_id", values[i])
			} else if value != nil {
				_m.CycleID = *value
			}
		case cycleconfig.FieldGWeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field g_weight", values[i])
			} else if value.Valid {
				_m.GWeight = value.Float64
			}
		case cycleconfig.FieldPWeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field p_weight", values[i])
			} else if value.Valid {
				_m.PWeight = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CycleConfig.
// This includes values selected through modifiers, order, etc.
func (_m *CycleConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCycle queries the "cycle" edge of the CycleConfig entity.
func (_m *CycleConfig) QueryCycle() *CycleQuery {
	return NewCycleConfigClient(_m.config).QueryCycle(_m)
}

// Update returns a builder for updating this CycleConfig.
// Note that you need to call CycleConfig.Unwrap() before calling this method if this CycleConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CycleConfig) Update() *CycleConfigUpdateOne {
	return NewCycleConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CycleConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CycleConfig) Unwrap() *CycleConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("internal: CycleConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CycleConfig) String() string {
	var builder strings.Builder
	builder.WriteString("CycleConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("cycle_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CycleID))
	builder.WriteString(", ")
	builder.WriteString("g_weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.GWeight))
	builder.WriteString(", ")
	builder.WriteString("p_weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.PWeight))
	builder.WriteByte(')')
	return builder.String()
}

// CycleConfigs is a parsable slice of CycleConfig.
type CycleConfigs []*CycleConfig
