// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/cycle"
	"github.com/sed-evaluacion-desempeno/api/internal/cycleconfig"
)

// CycleConfigCreate is the builder for creating a CycleConfig entity.
type CycleConfigCreate struct {
	config
	mutation *CycleConfigMutation
	hooks    []Hook
}

// SetCycleID sets the "cycle_id" field.
func (_c *CycleConfigCreate) SetCycleID(v uuid.UUID) *CycleConfigCreate {
	_c.mutation.SetCycleID(v)
	return _c
}

// SetGWeight sets the "g_weight" field.
func (_c *CycleConfigCreate) SetGWeight(v float64) *CycleConfigCreate {
	_c.mutation.SetGWeight(v)
	return _c
}

// SetNillableGWeight sets the "g_weight" field if the given value is not nil.
func (_c *CycleConfigCreate) SetNillableGWeight(v *float64) *CycleConfigCreate {
	if v != nil {
		_c.SetGWeight(*v)
	}
	return _c
}

// SetPWeight sets the "p_weight" field.
func (_c *CycleConfigCreate) SetPWeight(v float64) *CycleConfigCreate {
	_c.mutation.SetPWeight(v)
	return _c
}

// SetNillablePWeight sets the "p_weight" field if the given value is not nil.
func (_c *CycleConfigCreate) SetNillablePWeight(v *float64) *CycleConfigCreate {
	if v != nil {
		_c.SetPWeight(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CycleConfigCreate) SetID(v uuid.UUID) *CycleConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CycleConfigCreate) SetNillableID(v *uuid.UUID) *CycleConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCycle sets the "cycle" edge to the Cycle entity.
func (_c *CycleConfigCreate) SetCycle(v *Cycle) *CycleConfigCreate {
	return _c.SetCycleID(v.ID)
}

// Mutation returns the CycleConfigMutation object of the builder.
func (_c *CycleConfigCreate) Mutation() *CycleConfigMutation {
	return _c.mutation
}

// Save creates the CycleConfig in the database.
func (_c *CycleConfigCreate) Save(ctx context.Context) (*CycleConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CycleConfigCreate) SaveX(ctx context.Context) *CycleConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CycleConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CycleConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CycleConfigCreate) defaults() {
	if _, ok := _c.mutation.GWeight(); !ok {
		v := cycleconfig.DefaultGWeight
		_c.mutation.SetGWeight(v)
	}
	if _, ok := _c.mutation.PWeight(); !ok {
		v := cycleconfig.DefaultPWeight
		_c.mutation.SetPWeight(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := cycleconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CycleConfigCreate) check() error {
	if _, ok := _c.mutation.CycleID(); !ok {
		return &ValidationError{Name: "cycle_id", err: errors.New(`internal: missing required field "CycleConfig.cycle_id"`)}
	}
	if _, ok := _c.mutation.GWeight(); !ok {
		return &ValidationError{Name: "g_weight", err: errors.New(`internal: missing required field "CycleConfig.g_weight"`)}
	}
	if v, ok := _c.mutation.GWeight(); ok {
		if err := cycleconfig.GWeightValidator(v); err != nil {
			return &ValidationError{Name: "g_weight", err: fmt.Errorf(`internal: validator failed for field "CycleConfig.g_weight": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PWeight(); !ok {
		return &ValidationError{Name: "p_weight", err: errors.New(`internal: missing required field "CycleConfig.p_weight"`)}
	}
	if v, ok := _c.mutation.PWeight(); ok {
		if err := cycleconfig.PWeightValidator(v); err != nil {
			return &ValidationError{Name: "p_weight", err: fmt.Errorf(`internal: validator failed for field "CycleConfig.p_weight": %w`, err)}
		}
	}
	if len(_c.mutation.CycleIDs()) == 0 {
		return &ValidationError{Name: "cycle", err: errors.New(`internal: missing required edge "CycleConfig.cycle"`)}
	}
	return nil
}

func (_c *CycleConfigCreate) sqlSave(ctx context.Context) (*CycleConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CycleConfigCreate) createSpec() (*CycleConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &CycleConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cycleconfig.Table, sqlgraph.NewFieldSpec(cycleconfig.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GWeight(); ok {
		_spec.SetField(cycleconfig.FieldGWeight, field.TypeFloat64, value)
		_node.GWeight = value
	}
	if value, ok := _c.mutation.PWeight(); ok {
		_spec.SetField(cycleconfig.FieldPWeight, field.TypeFloat64, value)
		_node.PWeight = value
	}
	if nodes := _c.mutation.CycleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cycleconfig.CycleTable,
			Columns: []string{cycleconfig.CycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cycle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CycleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CycleConfigCreateBulk is the builder for creating many CycleConfig entities in bulk.
type CycleConfigCreateBulk struct {
	config
	err      error
	builders []*CycleConfigCreate
}

// Save creates the CycleConfig entities in the database.
func (_c *CycleConfigCreateBulk) Save(ctx context.Context) ([]*CycleConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CycleConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CycleConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CycleConfigCreateBulk) SaveX(ctx context.Context) []*CycleConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CycleConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CycleConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
