// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/employee"
	"github.com/sed-evaluacion-desempeno/api/internal/evaluation"
	"github.com/sed-evaluacion-desempeno/api/internal/evaluationprofile"
	"github.com/sed-evaluacion-desempeno/api/internal/evaluatorscope"
	"github.com/sed-evaluacion-desempeno/api/internal/goalassignment"
	"github.com/sed-evaluacion-desempeno/api/internal/goalcategory"
	"github.com/sed-evaluacion-desempeno/api/internal/nineboxentry"
	"github.com/sed-evaluacion-desempeno/api/internal/nineboxmatrix"
	"github.com/sed-evaluacion-desempeno/api/internal/orgnode"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// EmployeeUpdate is the builder for updating Employee entities.
type EmployeeUpdate struct {
	config
	hooks    []Hook
	mutation *EmployeeMutation
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (_u *EmployeeUpdate) Where(ps ...predicate.Employee) *EmployeeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmployeeUpdate) SetUpdatedAt(v time.Time) *EmployeeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *EmployeeUpdate) SetCreatedBy(v uuid.UUID) *EmployeeUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableCreatedBy(v *uuid.UUID) *EmployeeUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *EmployeeUpdate) SetUpdatedBy(v uuid.UUID) *EmployeeUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableUpdatedBy(v *uuid.UUID) *EmployeeUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *EmployeeUpdate) SetFirstName(v string) *EmployeeUpdate {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableFirstName(v *string) *EmployeeUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *EmployeeUpdate) SetLastName(v string) *EmployeeUpdate {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableLastName(v *string) *EmployeeUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetEmployeeNumber sets the "employee_number" field.
func (_u *EmployeeUpdate) SetEmployeeNumber(v string) *EmployeeUpdate {
	_u.mutation.SetEmployeeNumber(v)
	return _u
}

// SetNillableEmployeeNumber sets the "employee_number" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableEmployeeNumber(v *string) *EmployeeUpdate {
	if v != nil {
		_u.SetEmployeeNumber(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *EmployeeUpdate) SetEmail(v string) *EmployeeUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableEmail(v *string) *EmployeeUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *EmployeeUpdate) SetIsActive(v bool) *EmployeeUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableIsActive(v *bool) *EmployeeUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetOrgNodeID sets the "org_node_id" field.
func (_u *EmployeeUpdate) SetOrgNodeID(v uuid.UUID) *EmployeeUpdate {
	_u.mutation.SetOrgNodeID(v)
	return _u
}

// SetNillableOrgNodeID sets the "org_node_id" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableOrgNodeID(v *uuid.UUID) *EmployeeUpdate {
	if v != nil {
		_u.SetOrgNodeID(*v)
	}
	return _u
}

// SetManagerID sets the "manager_id" field.
func (_u *EmployeeUpdate) SetManagerID(v uuid.UUID) *EmployeeUpdate {
	_u.mutation.SetManagerID(v)
	return _u
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableManagerID(v *uuid.UUID) *EmployeeUpdate {
	if v != nil {
		_u.SetManagerID(*v)
	}
	return _u
}

// ClearManagerID clears the value of the "manager_id" field.
func (_u *EmployeeUpdate) ClearManagerID() *EmployeeUpdate {
	_u.mutation.ClearManagerID()
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *EmployeeUpdate) SetProfileID(v uuid.UUID) *EmployeeUpdate {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableProfileID(v *uuid.UUID) *EmployeeUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetOrgNode sets the "org_node" edge to the OrgNode entity.
func (_u *EmployeeUpdate) SetOrgNode(v *OrgNode) *EmployeeUpdate {
	return _u.SetOrgNodeID(v.ID)
}

// SetManager sets the "manager" edge to the Employee entity.
func (_u *EmployeeUpdate) SetManager(v *Employee) *EmployeeUpdate {
	return _u.SetManagerID(v.ID)
}

// AddDirectReportIDs adds the "direct_reports" edge to the Employee entity by IDs.
func (_u *EmployeeUpdate) AddDirectReportIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.AddDirectReportIDs(ids...)
	return _u
}

// AddDirectReports adds the "direct_reports" edges to the Employee entity.
func (_u *EmployeeUpdate) AddDirectReports(v ...*Employee) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDirectReportIDs(ids...)
}

// SetProfile sets the "profile" edge to the EvaluationProfile entity.
func (_u *EmployeeUpdate) SetProfile(v *EvaluationProfile) *EmployeeUpdate {
	return _u.SetProfileID(v.ID)
}

// AddEvaluatorScopeIDs adds the "evaluator_scopes" edge to the EvaluatorScope entity by IDs.
func (_u *EmployeeUpdate) AddEvaluatorScopeIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.AddEvaluatorScopeIDs(ids...)
	return _u
}

// AddEvaluatorScopes adds the "evaluator_scopes" edges to the EvaluatorScope entity.
func (_u *EmployeeUpdate) AddEvaluatorScopes(v ...*EvaluatorScope) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEvaluatorScopeIDs(ids...)
}

// AddGoalCategoryIDs adds the "goal_categories" edge to the GoalCategory entity by IDs.
func (_u *EmployeeUpdate) AddGoalCategoryIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.AddGoalCategoryIDs(ids...)
	return _u
}

// AddGoalCategories adds the "goal_categories" edges to the GoalCategory entity.
func (_u *EmployeeUpdate) AddGoalCategories(v ...*GoalCategory) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGoalCategoryIDs(ids...)
}

// AddGoalAssignmentIDs adds the "goal_assignments" edge to the GoalAssignment entity by IDs.
func (_u *EmployeeUpdate) AddGoalAssignmentIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.AddGoalAssignmentIDs(ids...)
	return _u
}

// AddGoalAssignments adds the "goal_assignments" edges to the GoalAssignment entity.
func (_u *EmployeeUpdate) AddGoalAssignments(v ...*GoalAssignment) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGoalAssignmentIDs(ids...)
}

// AddEvaluationIDs adds the "evaluations" edge to the Evaluation entity by IDs.
func (_u *EmployeeUpdate) AddEvaluationIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.AddEvaluationIDs(ids...)
	return _u
}

// AddEvaluations adds the "evaluations" edges to the Evaluation entity.
func (_u *EmployeeUpdate) AddEvaluations(v ...*Evaluation) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEvaluationIDs(ids...)
}

// AddNineBoxMatrixIDs adds the "nine_box_matrices" edge to the NineBoxMatrix entity by IDs.
func (_u *EmployeeUpdate) AddNineBoxMatrixIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.AddNineBoxMatrixIDs(ids...)
	return _u
}

// AddNineBoxMatrices adds the "nine_box_matrices" edges to the NineBoxMatrix entity.
func (_u *EmployeeUpdate) AddNineBoxMatrices(v ...*NineBoxMatrix) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNineBoxMatrixIDs(ids...)
}

// AddNineBoxEntryIDs adds the "nine_box_entries" edge to the NineBoxEntry entity by IDs.
func (_u *EmployeeUpdate) AddNineBoxEntryIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.AddNineBoxEntryIDs(ids...)
	return _u
}

// AddNineBoxEntries adds the "nine_box_entries" edges to the NineBoxEntry entity.
func (_u *EmployeeUpdate) AddNineBoxEntries(v ...*NineBoxEntry) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNineBoxEntryIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (_u *EmployeeUpdate) Mutation() *EmployeeMutation {
	return _u.mutation
}

// ClearOrgNode clears the "org_node" edge to the OrgNode entity.
func (_u *EmployeeUpdate) ClearOrgNode() *EmployeeUpdate {
	_u.mutation.ClearOrgNode()
	return _u
}

// ClearManager clears the "manager" edge to the Employee entity.
func (_u *EmployeeUpdate) ClearManager() *EmployeeUpdate {
	_u.mutation.ClearManager()
	return _u
}

// ClearDirectReports clears all "direct_reports" edges to the Employee entity.
func (_u *EmployeeUpdate) ClearDirectReports() *EmployeeUpdate {
	_u.mutation.ClearDirectReports()
	return _u
}

// RemoveDirectReportIDs removes the "direct_reports" edge to Employee entities by IDs.
func (_u *EmployeeUpdate) RemoveDirectReportIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.RemoveDirectReportIDs(ids...)
	return _u
}

// RemoveDirectReports removes "direct_reports" edges to Employee entities.
func (_u *EmployeeUpdate) RemoveDirectReports(v ...*Employee) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDirectReportIDs(ids...)
}

// ClearProfile clears the "profile" edge to the EvaluationProfile entity.
func (_u *EmployeeUpdate) ClearProfile() *EmployeeUpdate {
	_u.mutation.ClearProfile()
	return _u
}

// ClearEvaluatorScopes clears all "evaluator_scopes" edges to the EvaluatorScope entity.
func (_u *EmployeeUpdate) ClearEvaluatorScopes() *EmployeeUpdate {
	_u.mutation.ClearEvaluatorScopes()
	return _u
}

// RemoveEvaluatorScopeIDs removes the "evaluator_scopes" edge to EvaluatorScope entities by IDs.
func (_u *EmployeeUpdate) RemoveEvaluatorScopeIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.RemoveEvaluatorScopeIDs(ids...)
	return _u
}

// RemoveEvaluatorScopes removes "evaluator_scopes" edges to EvaluatorScope entities.
func (_u *EmployeeUpdate) RemoveEvaluatorScopes(v ...*EvaluatorScope) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEvaluatorScopeIDs(ids...)
}

// ClearGoalCategories clears all "goal_categories" edges to the GoalCategory entity.
func (_u *EmployeeUpdate) ClearGoalCategories() *EmployeeUpdate {
	_u.mutation.ClearGoalCategories()
	return _u
}

// RemoveGoalCategoryIDs removes the "goal_categories" edge to GoalCategory entities by IDs.
func (_u *EmployeeUpdate) RemoveGoalCategoryIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.RemoveGoalCategoryIDs(ids...)
	return _u
}

// RemoveGoalCategories removes "goal_categories" edges to GoalCategory entities.
func (_u *EmployeeUpdate) RemoveGoalCategories(v ...*GoalCategory) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGoalCategoryIDs(ids...)
}

// ClearGoalAssignments clears all "goal_assignments" edges to the GoalAssignment entity.
func (_u *EmployeeUpdate) ClearGoalAssignments() *EmployeeUpdate {
	_u.mutation.ClearGoalAssignments()
	return _u
}

// RemoveGoalAssignmentIDs removes the "goal_assignments" edge to GoalAssignment entities by IDs.
func (_u *EmployeeUpdate) RemoveGoalAssignmentIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.RemoveGoalAssignmentIDs(ids...)
	return _u
}

// RemoveGoalAssignments removes "goal_assignments" edges to GoalAssignment entities.
func (_u *EmployeeUpdate) RemoveGoalAssignments(v ...*GoalAssignment) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGoalAssignmentIDs(ids...)
}

// ClearEvaluations clears all "evaluations" edges to the Evaluation entity.
func (_u *EmployeeUpdate) ClearEvaluations() *EmployeeUpdate {
	_u.mutation.ClearEvaluations()
	return _u
}

// RemoveEvaluationIDs removes the "evaluations" edge to Evaluation entities by IDs.
func (_u *EmployeeUpdate) RemoveEvaluationIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.RemoveEvaluationIDs(ids...)
	return _u
}

// RemoveEvaluations removes "evaluations" edges to Evaluation entities.
func (_u *EmployeeUpdate) RemoveEvaluations(v ...*Evaluation) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEvaluationIDs(ids...)
}

// ClearNineBoxMatrices clears all "nine_box_matrices" edges to the NineBoxMatrix entity.
func (_u *EmployeeUpdate) ClearNineBoxMatrices() *EmployeeUpdate {
	_u.mutation.ClearNineBoxMatrices()
	return _u
}

// RemoveNineBoxMatrixIDs removes the "nine_box_matrices" edge to NineBoxMatrix entities by IDs.
func (_u *EmployeeUpdate) RemoveNineBoxMatrixIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.RemoveNineBoxMatrixIDs(ids...)
	return _u
}

// RemoveNineBoxMatrices removes "nine_box_matrices" edges to NineBoxMatrix entities.
func (_u *EmployeeUpdate) RemoveNineBoxMatrices(v ...*NineBoxMatrix) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNineBoxMatrixIDs(ids...)
}

// ClearNineBoxEntries clears all "nine_box_entries" edges to the NineBoxEntry entity.
func (_u *EmployeeUpdate) ClearNineBoxEntries() *EmployeeUpdate {
	_u.mutation.ClearNineBoxEntries()
	return _u
}

// RemoveNineBoxEntryIDs removes the "nine_box_entries" edge to NineBoxEntry entities by IDs.
func (_u *EmployeeUpdate) RemoveNineBoxEntryIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.RemoveNineBoxEntryIDs(ids...)
	return _u
}

// RemoveNineBoxEntries removes "nine_box_entries" edges to NineBoxEntry entities.
func (_u *EmployeeUpdate) RemoveNineBoxEntries(v ...*NineBoxEntry) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNineBoxEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmployeeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmployeeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmployeeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmployeeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmployeeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := employee.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmployeeUpdate) check() error {
	if v, ok := _u.mutation.FirstName(); ok {
		if err := employee.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`internal: validator failed for field "Employee.first_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastName(); ok {
		if err := employee.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`internal: validator failed for field "Employee.last_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EmployeeNumber(); ok {
		if err := employee.EmployeeNumberValidator(v); err != nil {
			return &ValidationError{Name: "employee_number", err: fmt.Errorf(`internal: validator failed for field "Employee.employee_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := employee.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`internal: validator failed for field "Employee.email": %w`, err)}
		}
	}
	if _u.mutation.OrgNodeCleared() && len(_u.mutation.OrgNodeIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "Employee.org_node"`)
	}
	if _u.mutation.ProfileCleared() && len(_u.mutation.ProfileIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "Employee.profile"`)
	}
	return nil
}

func (_u *EmployeeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(employee.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(employee.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(employee.FieldUpdatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(employee.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(employee.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmployeeNumber(); ok {
		_spec.SetField(employee.FieldEmployeeNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(employee.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(employee.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.OrgNodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.OrgNodeTable,
			Columns: []string{employee.OrgNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgnode.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrgNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.OrgNodeTable,
			Columns: []string{employee.OrgNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgnode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DirectReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.DirectReportsTable,
			Columns: []string{employee.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDirectReportsIDs(); len(nodes) > 0 && !_u.mutation.DirectReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.DirectReportsTable,
			Columns: []string{employee.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DirectReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.DirectReportsTable,
			Columns: []string{employee.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ProfileTable,
			Columns: []string{employee.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationprofile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ProfileTable,
			Columns: []string{employee.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EvaluatorScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluatorScopesTable,
			Columns: []string{employee.EvaluatorScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluatorscope.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEvaluatorScopesIDs(); len(nodes) > 0 && !_u.mutation.EvaluatorScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluatorScopesTable,
			Columns: []string{employee.EvaluatorScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluatorscope.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvaluatorScopesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluatorScopesTable,
			Columns: []string{employee.EvaluatorScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluatorscope.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GoalCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalCategoriesTable,
			Columns: []string{employee.GoalCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalcategory.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGoalCategoriesIDs(); len(nodes) > 0 && !_u.mutation.GoalCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalCategoriesTable,
			Columns: []string{employee.GoalCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalcategory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoalCategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalCategoriesTable,
			Columns: []string{employee.GoalCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalcategory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GoalAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalAssignmentsTable,
			Columns: []string{employee.GoalAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGoalAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.GoalAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalAssignmentsTable,
			Columns: []string{employee.GoalAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoalAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalAssignmentsTable,
			Columns: []string{employee.GoalAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EvaluationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluationsTable,
			Columns: []string{employee.EvaluationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEvaluationsIDs(); len(nodes) > 0 && !_u.mutation.EvaluationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluationsTable,
			Columns: []string{employee.EvaluationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvaluationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluationsTable,
			Columns: []string{employee.EvaluationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NineBoxMatricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxMatricesTable,
			Columns: []string{employee.NineBoxMatricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxmatrix.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNineBoxMatricesIDs(); len(nodes) > 0 && !_u.mutation.NineBoxMatricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxMatricesTable,
			Columns: []string{employee.NineBoxMatricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxmatrix.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NineBoxMatricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxMatricesTable,
			Columns: []string{employee.NineBoxMatricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxmatrix.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NineBoxEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxEntriesTable,
			Columns: []string{employee.NineBoxEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNineBoxEntriesIDs(); len(nodes) > 0 && !_u.mutation.NineBoxEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxEntriesTable,
			Columns: []string{employee.NineBoxEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NineBoxEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxEntriesTable,
			Columns: []string{employee.NineBoxEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmployeeUpdateOne is the builder for updating a single Employee entity.
type EmployeeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmployeeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmployeeUpdateOne) SetUpdatedAt(v time.Time) *EmployeeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *EmployeeUpdateOne) SetCreatedBy(v uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *EmployeeUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *EmployeeUpdateOne) SetUpdatedBy(v uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *EmployeeUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *EmployeeUpdateOne) SetFirstName(v string) *EmployeeUpdateOne {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableFirstName(v *string) *EmployeeUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *EmployeeUpdateOne) SetLastName(v string) *EmployeeUpdateOne {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableLastName(v *string) *EmployeeUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetEmployeeNumber sets the "employee_number" field.
func (_u *EmployeeUpdateOne) SetEmployeeNumber(v string) *EmployeeUpdateOne {
	_u.mutation.SetEmployeeNumber(v)
	return _u
}

// SetNillableEmployeeNumber sets the "employee_number" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableEmployeeNumber(v *string) *EmployeeUpdateOne {
	if v != nil {
		_u.SetEmployeeNumber(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *EmployeeUpdateOne) SetEmail(v string) *EmployeeUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableEmail(v *string) *EmployeeUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *EmployeeUpdateOne) SetIsActive(v bool) *EmployeeUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableIsActive(v *bool) *EmployeeUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetOrgNodeID sets the "org_node_id" field.
func (_u *EmployeeUpdateOne) SetOrgNodeID(v uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.SetOrgNodeID(v)
	return _u
}

// SetNillableOrgNodeID sets the "org_node_id" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableOrgNodeID(v *uuid.UUID) *EmployeeUpdateOne {
	if v != nil {
		_u.SetOrgNodeID(*v)
	}
	return _u
}

// SetManagerID sets the "manager_id" field.
func (_u *EmployeeUpdateOne) SetManagerID(v uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.SetManagerID(v)
	return _u
}

// SetNillableManagerID sets the "manager_id" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableManagerID(v *uuid.UUID) *EmployeeUpdateOne {
	if v != nil {
		_u.SetManagerID(*v)
	}
	return _u
}

// ClearManagerID clears the value of the "manager_id" field.
func (_u *EmployeeUpdateOne) ClearManagerID() *EmployeeUpdateOne {
	_u.mutation.ClearManagerID()
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *EmployeeUpdateOne) SetProfileID(v uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableProfileID(v *uuid.UUID) *EmployeeUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetOrgNode sets the "org_node" edge to the OrgNode entity.
func (_u *EmployeeUpdateOne) SetOrgNode(v *OrgNode) *EmployeeUpdateOne {
	return _u.SetOrgNodeID(v.ID)
}

// SetManager sets the "manager" edge to the Employee entity.
func (_u *EmployeeUpdateOne) SetManager(v *Employee) *EmployeeUpdateOne {
	return _u.SetManagerID(v.ID)
}

// AddDirectReportIDs adds the "direct_reports" edge to the Employee entity by IDs.
func (_u *EmployeeUpdateOne) AddDirectReportIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.AddDirectReportIDs(ids...)
	return _u
}

// AddDirectReports adds the "direct_reports" edges to the Employee entity.
func (_u *EmployeeUpdateOne) AddDirectReports(v ...*Employee) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDirectReportIDs(ids...)
}

// SetProfile sets the "profile" edge to the EvaluationProfile entity.
func (_u *EmployeeUpdateOne) SetProfile(v *EvaluationProfile) *EmployeeUpdateOne {
	return _u.SetProfileID(v.ID)
}

// AddEvaluatorScopeIDs adds the "evaluator_scopes" edge to the EvaluatorScope entity by IDs.
func (_u *EmployeeUpdateOne) AddEvaluatorScopeIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.AddEvaluatorScopeIDs(ids...)
	return _u
}

// AddEvaluatorScopes adds the "evaluator_scopes" edges to the EvaluatorScope entity.
func (_u *EmployeeUpdateOne) AddEvaluatorScopes(v ...*EvaluatorScope) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEvaluatorScopeIDs(ids...)
}

// AddGoalCategoryIDs adds the "goal_categories" edge to the GoalCategory entity by IDs.
func (_u *EmployeeUpdateOne) AddGoalCategoryIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.AddGoalCategoryIDs(ids...)
	return _u
}

// AddGoalCategories adds the "goal_categories" edges to the GoalCategory entity.
func (_u *EmployeeUpdateOne) AddGoalCategories(v ...*GoalCategory) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGoalCategoryIDs(ids...)
}

// AddGoalAssignmentIDs adds the "goal_assignments" edge to the GoalAssignment entity by IDs.
func (_u *EmployeeUpdateOne) AddGoalAssignmentIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.AddGoalAssignmentIDs(ids...)
	return _u
}

// AddGoalAssignments adds the "goal_assignments" edges to the GoalAssignment entity.
func (_u *EmployeeUpdateOne) AddGoalAssignments(v ...*GoalAssignment) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGoalAssignmentIDs(ids...)
}

// AddEvaluationIDs adds the "evaluations" edge to the Evaluation entity by IDs.
func (_u *EmployeeUpdateOne) AddEvaluationIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.AddEvaluationIDs(ids...)
	return _u
}

// AddEvaluations adds the "evaluations" edges to the Evaluation entity.
func (_u *EmployeeUpdateOne) AddEvaluations(v ...*Evaluation) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEvaluationIDs(ids...)
}

// AddNineBoxMatrixIDs adds the "nine_box_matrices" edge to the NineBoxMatrix entity by IDs.
func (_u *EmployeeUpdateOne) AddNineBoxMatrixIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.AddNineBoxMatrixIDs(ids...)
	return _u
}

// AddNineBoxMatrices adds the "nine_box_matrices" edges to the NineBoxMatrix entity.
func (_u *EmployeeUpdateOne) AddNineBoxMatrices(v ...*NineBoxMatrix) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNineBoxMatrixIDs(ids...)
}

// AddNineBoxEntryIDs adds the "nine_box_entries" edge to the NineBoxEntry entity by IDs.
func (_u *EmployeeUpdateOne) AddNineBoxEntryIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.AddNineBoxEntryIDs(ids...)
	return _u
}

// AddNineBoxEntries adds the "nine_box_entries" edges to the NineBoxEntry entity.
func (_u *EmployeeUpdateOne) AddNineBoxEntries(v ...*NineBoxEntry) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNineBoxEntryIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (_u *EmployeeUpdateOne) Mutation() *EmployeeMutation {
	return _u.mutation
}

// ClearOrgNode clears the "org_node" edge to the OrgNode entity.
func (_u *EmployeeUpdateOne) ClearOrgNode() *EmployeeUpdateOne {
	_u.mutation.ClearOrgNode()
	return _u
}

// ClearManager clears the "manager" edge to the Employee entity.
func (_u *EmployeeUpdateOne) ClearManager() *EmployeeUpdateOne {
	_u.mutation.ClearManager()
	return _u
}

// ClearDirectReports clears all "direct_reports" edges to the Employee entity.
func (_u *EmployeeUpdateOne) ClearDirectReports() *EmployeeUpdateOne {
	_u.mutation.ClearDirectReports()
	return _u
}

// RemoveDirectReportIDs removes the "direct_reports" edge to Employee entities by IDs.
func (_u *EmployeeUpdateOne) RemoveDirectReportIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.RemoveDirectReportIDs(ids...)
	return _u
}

// RemoveDirectReports removes "direct_reports" edges to Employee entities.
func (_u *EmployeeUpdateOne) RemoveDirectReports(v ...*Employee) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDirectReportIDs(ids...)
}

// ClearProfile clears the "profile" edge to the EvaluationProfile entity.
func (_u *EmployeeUpdateOne) ClearProfile() *EmployeeUpdateOne {
	_u.mutation.ClearProfile()
	return _u
}

// ClearEvaluatorScopes clears all "evaluator_scopes" edges to the EvaluatorScope entity.
func (_u *EmployeeUpdateOne) ClearEvaluatorScopes() *EmployeeUpdateOne {
	_u.mutation.ClearEvaluatorScopes()
	return _u
}

// RemoveEvaluatorScopeIDs removes the "evaluator_scopes" edge to EvaluatorScope entities by IDs.
func (_u *EmployeeUpdateOne) RemoveEvaluatorScopeIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.RemoveEvaluatorScopeIDs(ids...)
	return _u
}

// RemoveEvaluatorScopes removes "evaluator_scopes" edges to EvaluatorScope entities.
func (_u *EmployeeUpdateOne) RemoveEvaluatorScopes(v ...*EvaluatorScope) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEvaluatorScopeIDs(ids...)
}

// ClearGoalCategories clears all "goal_categories" edges to the GoalCategory entity.
func (_u *EmployeeUpdateOne) ClearGoalCategories() *EmployeeUpdateOne {
	_u.mutation.ClearGoalCategories()
	return _u
}

// RemoveGoalCategoryIDs removes the "goal_categories" edge to GoalCategory entities by IDs.
func (_u *EmployeeUpdateOne) RemoveGoalCategoryIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.RemoveGoalCategoryIDs(ids...)
	return _u
}

// RemoveGoalCategories removes "goal_categories" edges to GoalCategory entities.
func (_u *EmployeeUpdateOne) RemoveGoalCategories(v ...*GoalCategory) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGoalCategoryIDs(ids...)
}

// ClearGoalAssignments clears all "goal_assignments" edges to the GoalAssignment entity.
func (_u *EmployeeUpdateOne) ClearGoalAssignments() *EmployeeUpdateOne {
	_u.mutation.ClearGoalAssignments()
	return _u
}

// RemoveGoalAssignmentIDs removes the "goal_assignments" edge to GoalAssignment entities by IDs.
func (_u *EmployeeUpdateOne) RemoveGoalAssignmentIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.RemoveGoalAssignmentIDs(ids...)
	return _u
}

// RemoveGoalAssignments removes "goal_assignments" edges to GoalAssignment entities.
func (_u *EmployeeUpdateOne) RemoveGoalAssignments(v ...*GoalAssignment) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGoalAssignmentIDs(ids...)
}

// ClearEvaluations clears all "evaluations" edges to the Evaluation entity.
func (_u *EmployeeUpdateOne) ClearEvaluations() *EmployeeUpdateOne {
	_u.mutation.ClearEvaluations()
	return _u
}

// RemoveEvaluationIDs removes the "evaluations" edge to Evaluation entities by IDs.
func (_u *EmployeeUpdateOne) RemoveEvaluationIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.RemoveEvaluationIDs(ids...)
	return _u
}

// RemoveEvaluations removes "evaluations" edges to Evaluation entities.
func (_u *EmployeeUpdateOne) RemoveEvaluations(v ...*Evaluation) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEvaluationIDs(ids...)
}

// ClearNineBoxMatrices clears all "nine_box_matrices" edges to the NineBoxMatrix entity.
func (_u *EmployeeUpdateOne) ClearNineBoxMatrices() *EmployeeUpdateOne {
	_u.mutation.ClearNineBoxMatrices()
	return _u
}

// RemoveNineBoxMatrixIDs removes the "nine_box_matrices" edge to NineBoxMatrix entities by IDs.
func (_u *EmployeeUpdateOne) RemoveNineBoxMatrixIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.RemoveNineBoxMatrixIDs(ids...)
	return _u
}

// RemoveNineBoxMatrices removes "nine_box_matrices" edges to NineBoxMatrix entities.
func (_u *EmployeeUpdateOne) RemoveNineBoxMatrices(v ...*NineBoxMatrix) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNineBoxMatrixIDs(ids...)
}

// ClearNineBoxEntries clears all "nine_box_entries" edges to the NineBoxEntry entity.
func (_u *EmployeeUpdateOne) ClearNineBoxEntries() *EmployeeUpdateOne {
	_u.mutation.ClearNineBoxEntries()
	return _u
}

// RemoveNineBoxEntryIDs removes the "nine_box_entries" edge to NineBoxEntry entities by IDs.
func (_u *EmployeeUpdateOne) RemoveNineBoxEntryIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.RemoveNineBoxEntryIDs(ids...)
	return _u
}

// RemoveNineBoxEntries removes "nine_box_entries" edges to NineBoxEntry entities.
func (_u *EmployeeUpdateOne) RemoveNineBoxEntries(v ...*NineBoxEntry) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNineBoxEntryIDs(ids...)
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (_u *EmployeeUpdateOne) Where(ps ...predicate.Employee) *EmployeeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmployeeUpdateOne) Select(field string, fields ...string) *EmployeeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Employee entity.
func (_u *EmployeeUpdateOne) Save(ctx context.Context) (*Employee, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmployeeUpdateOne) SaveX(ctx context.Context) *Employee {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmployeeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmployeeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EmployeeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := employee.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmployeeUpdateOne) check() error {
	if v, ok := _u.mutation.FirstName(); ok {
		if err := employee.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`internal: validator failed for field "Employee.first_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastName(); ok {
		if err := employee.LastNameValidator(v); err != nil {
			return &ValidationError{Name: "last_name", err: fmt.Errorf(`internal: validator failed for field "Employee.last_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EmployeeNumber(); ok {
		if err := employee.EmployeeNumberValidator(v); err != nil {
			return &ValidationError{Name: "employee_number", err: fmt.Errorf(`internal: validator failed for field "Employee.employee_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := employee.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`internal: validator failed for field "Employee.email": %w`, err)}
		}
	}
	if _u.mutation.OrgNodeCleared() && len(_u.mutation.OrgNodeIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "Employee.org_node"`)
	}
	if _u.mutation.ProfileCleared() && len(_u.mutation.ProfileIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "Employee.profile"`)
	}
	return nil
}

func (_u *EmployeeUpdateOne) sqlSave(ctx context.Context) (_node *Employee, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`internal: missing "Employee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employee.FieldID)
		for _, f := range fields {
			if !employee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
			}
			if f != employee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(employee.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(employee.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(employee.FieldUpdatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(employee.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(employee.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmployeeNumber(); ok {
		_spec.SetField(employee.FieldEmployeeNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(employee.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(employee.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.OrgNodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.OrgNodeTable,
			Columns: []string{employee.OrgNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgnode.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrgNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.OrgNodeTable,
			Columns: []string{employee.OrgNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgnode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   employee.ManagerTable,
			Columns: []string{employee.ManagerColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DirectReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.DirectReportsTable,
			Columns: []string{employee.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDirectReportsIDs(); len(nodes) > 0 && !_u.mutation.DirectReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.DirectReportsTable,
			Columns: []string{employee.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DirectReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   employee.DirectReportsTable,
			Columns: []string{employee.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ProfileTable,
			Columns: []string{employee.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationprofile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ProfileTable,
			Columns: []string{employee.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluationprofile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EvaluatorScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluatorScopesTable,
			Columns: []string{employee.EvaluatorScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluatorscope.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEvaluatorScopesIDs(); len(nodes) > 0 && !_u.mutation.EvaluatorScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluatorScopesTable,
			Columns: []string{employee.EvaluatorScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluatorscope.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvaluatorScopesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluatorScopesTable,
			Columns: []string{employee.EvaluatorScopesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluatorscope.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GoalCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalCategoriesTable,
			Columns: []string{employee.GoalCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalcategory.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGoalCategoriesIDs(); len(nodes) > 0 && !_u.mutation.GoalCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalCategoriesTable,
			Columns: []string{employee.GoalCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalcategory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoalCategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalCategoriesTable,
			Columns: []string{employee.GoalCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalcategory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GoalAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalAssignmentsTable,
			Columns: []string{employee.GoalAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGoalAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.GoalAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalAssignmentsTable,
			Columns: []string{employee.GoalAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoalAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.GoalAssignmentsTable,
			Columns: []string{employee.GoalAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goalassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EvaluationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluationsTable,
			Columns: []string{employee.EvaluationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEvaluationsIDs(); len(nodes) > 0 && !_u.mutation.EvaluationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluationsTable,
			Columns: []string{employee.EvaluationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvaluationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.EvaluationsTable,
			Columns: []string{employee.EvaluationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NineBoxMatricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxMatricesTable,
			Columns: []string{employee.NineBoxMatricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxmatrix.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNineBoxMatricesIDs(); len(nodes) > 0 && !_u.mutation.NineBoxMatricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxMatricesTable,
			Columns: []string{employee.NineBoxMatricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxmatrix.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NineBoxMatricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxMatricesTable,
			Columns: []string{employee.NineBoxMatricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxmatrix.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NineBoxEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxEntriesTable,
			Columns: []string{employee.NineBoxEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxentry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNineBoxEntriesIDs(); len(nodes) > 0 && !_u.mutation.NineBoxEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxEntriesTable,
			Columns: []string{employee.NineBoxEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NineBoxEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.NineBoxEntriesTable,
			Columns: []string{employee.NineBoxEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxentry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Employee{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
