// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/evaluation"
	"github.com/sed-evaluacion-desempeno/api/internal/evaluationgoal"
	"github.com/sed-evaluacion-desempeno/api/internal/goal"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// EvaluationGoalUpdate is the builder for updating EvaluationGoal entities.
type EvaluationGoalUpdate struct {
	config
	hooks    []Hook
	mutation *EvaluationGoalMutation
}

// Where appends a list predicates to the EvaluationGoalUpdate builder.
func (_u *EvaluationGoalUpdate) Where(ps ...predicate.EvaluationGoal) *EvaluationGoalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvaluationGoalUpdate) SetUpdatedAt(v time.Time) *EvaluationGoalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFinalRating sets the "final_rating" field.
func (_u *EvaluationGoalUpdate) SetFinalRating(v int) *EvaluationGoalUpdate {
	_u.mutation.ResetFinalRating()
	_u.mutation.SetFinalRating(v)
	return _u
}

// SetNillableFinalRating sets the "final_rating" field if the given value is not nil.
func (_u *EvaluationGoalUpdate) SetNillableFinalRating(v *int) *EvaluationGoalUpdate {
	if v != nil {
		_u.SetFinalRating(*v)
	}
	return _u
}

// AddFinalRating adds value to the "final_rating" field.
func (_u *EvaluationGoalUpdate) AddFinalRating(v int) *EvaluationGoalUpdate {
	_u.mutation.AddFinalRating(v)
	return _u
}

// ClearFinalRating clears the value of the "final_rating" field.
func (_u *EvaluationGoalUpdate) ClearFinalRating() *EvaluationGoalUpdate {
	_u.mutation.ClearFinalRating()
	return _u
}

// SetFinalComments sets the "final_comments" field.
func (_u *EvaluationGoalUpdate) SetFinalComments(v string) *EvaluationGoalUpdate {
	_u.mutation.SetFinalComments(v)
	return _u
}

// SetNillableFinalComments sets the "final_comments" field if the given value is not nil.
func (_u *EvaluationGoalUpdate) SetNillableFinalComments(v *string) *EvaluationGoalUpdate {
	if v != nil {
		_u.SetFinalComments(*v)
	}
	return _u
}

// ClearFinalComments clears the value of the "final_comments" field.
func (_u *EvaluationGoalUpdate) ClearFinalComments() *EvaluationGoalUpdate {
	_u.mutation.ClearFinalComments()
	return _u
}

// SetEvaluationID sets the "evaluation_id" field.
func (_u *EvaluationGoalUpdate) SetEvaluationID(v uuid.UUID) *EvaluationGoalUpdate {
	_u.mutation.SetEvaluationID(v)
	return _u
}

// SetNillableEvaluationID sets the "evaluation_id" field if the given value is not nil.
func (_u *EvaluationGoalUpdate) SetNillableEvaluationID(v *uuid.UUID) *EvaluationGoalUpdate {
	if v != nil {
		_u.SetEvaluationID(*v)
	}
	return _u
}

// SetGoalID sets the "goal_id" field.
func (_u *EvaluationGoalUpdate) SetGoalID(v uuid.UUID) *EvaluationGoalUpdate {
	_u.mutation.SetGoalID(v)
	return _u
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (_u *EvaluationGoalUpdate) SetNillableGoalID(v *uuid.UUID) *EvaluationGoalUpdate {
	if v != nil {
		_u.SetGoalID(*v)
	}
	return _u
}

// SetEvaluation sets the "evaluation" edge to the Evaluation entity.
func (_u *EvaluationGoalUpdate) SetEvaluation(v *Evaluation) *EvaluationGoalUpdate {
	return _u.SetEvaluationID(v.ID)
}

// SetGoal sets the "goal" edge to the Goal entity.
func (_u *EvaluationGoalUpdate) SetGoal(v *Goal) *EvaluationGoalUpdate {
	return _u.SetGoalID(v.ID)
}

// Mutation returns the EvaluationGoalMutation object of the builder.
func (_u *EvaluationGoalUpdate) Mutation() *EvaluationGoalMutation {
	return _u.mutation
}

// ClearEvaluation clears the "evaluation" edge to the Evaluation entity.
func (_u *EvaluationGoalUpdate) ClearEvaluation() *EvaluationGoalUpdate {
	_u.mutation.ClearEvaluation()
	return _u
}

// ClearGoal clears the "goal" edge to the Goal entity.
func (_u *EvaluationGoalUpdate) ClearGoal() *EvaluationGoalUpdate {
	_u.mutation.ClearGoal()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EvaluationGoalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvaluationGoalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EvaluationGoalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvaluationGoalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvaluationGoalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evaluationgoal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvaluationGoalUpdate) check() error {
	if v, ok := _u.mutation.FinalRating(); ok {
		if err := evaluationgoal.FinalRatingValidator(v); err != nil {
			return &ValidationError{Name: "final_rating", err: fmt.Errorf(`internal: validator failed for field "EvaluationGoal.final_rating": %w`, err)}
		}
	}
	if _u.mutation.EvaluationCleared() && len(_u.mutation.EvaluationIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "EvaluationGoal.evaluation"`)
	}
	if _u.mutation.GoalCleared() && len(_u.mutation.GoalIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "EvaluationGoal.goal"`)
	}
	return nil
}

func (_u *EvaluationGoalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evaluationgoal.Table, evaluationgoal.Columns, sqlgraph.NewFieldSpec(evaluationgoal.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evaluationgoal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinalRating(); ok {
		_spec.SetField(evaluationgoal.FieldFinalRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFinalRating(); ok {
		_spec.AddField(evaluationgoal.FieldFinalRating, field.TypeInt, value)
	}
	if _u.mutation.FinalRatingCleared() {
		_spec.ClearField(evaluationgoal.FieldFinalRating, field.TypeInt)
	}
	if value, ok := _u.mutation.FinalComments(); ok {
		_spec.SetField(evaluationgoal.FieldFinalComments, field.TypeString, value)
	}
	if _u.mutation.FinalCommentsCleared() {
		_spec.ClearField(evaluationgoal.FieldFinalComments, field.TypeString)
	}
	if _u.mutation.EvaluationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationgoal.EvaluationTable,
			Columns: []string{evaluationgoal.EvaluationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvaluationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationgoal.EvaluationTable,
			Columns: []string{evaluationgoal.EvaluationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GoalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationgoal.GoalTable,
			Columns: []string{evaluationgoal.GoalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationgoal.GoalTable,
			Columns: []string{evaluationgoal.GoalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evaluationgoal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EvaluationGoalUpdateOne is the builder for updating a single EvaluationGoal entity.
type EvaluationGoalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EvaluationGoalMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EvaluationGoalUpdateOne) SetUpdatedAt(v time.Time) *EvaluationGoalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFinalRating sets the "final_rating" field.
func (_u *EvaluationGoalUpdateOne) SetFinalRating(v int) *EvaluationGoalUpdateOne {
	_u.mutation.ResetFinalRating()
	_u.mutation.SetFinalRating(v)
	return _u
}

// SetNillableFinalRating sets the "final_rating" field if the given value is not nil.
func (_u *EvaluationGoalUpdateOne) SetNillableFinalRating(v *int) *EvaluationGoalUpdateOne {
	if v != nil {
		_u.SetFinalRating(*v)
	}
	return _u
}

// AddFinalRating adds value to the "final_rating" field.
func (_u *EvaluationGoalUpdateOne) AddFinalRating(v int) *EvaluationGoalUpdateOne {
	_u.mutation.AddFinalRating(v)
	return _u
}

// ClearFinalRating clears the value of the "final_rating" field.
func (_u *EvaluationGoalUpdateOne) ClearFinalRating() *EvaluationGoalUpdateOne {
	_u.mutation.ClearFinalRating()
	return _u
}

// SetFinalComments sets the "final_comments" field.
func (_u *EvaluationGoalUpdateOne) SetFinalComments(v string) *EvaluationGoalUpdateOne {
	_u.mutation.SetFinalComments(v)
	return _u
}

// SetNillableFinalComments sets the "final_comments" field if the given value is not nil.
func (_u *EvaluationGoalUpdateOne) SetNillableFinalComments(v *string) *EvaluationGoalUpdateOne {
	if v != nil {
		_u.SetFinalComments(*v)
	}
	return _u
}

// ClearFinalComments clears the value of the "final_comments" field.
func (_u *EvaluationGoalUpdateOne) ClearFinalComments() *EvaluationGoalUpdateOne {
	_u.mutation.ClearFinalComments()
	return _u
}

// SetEvaluationID sets the "evaluation_id" field.
func (_u *EvaluationGoalUpdateOne) SetEvaluationID(v uuid.UUID) *EvaluationGoalUpdateOne {
	_u.mutation.SetEvaluationID(v)
	return _u
}

// SetNillableEvaluationID sets the "evaluation_id" field if the given value is not nil.
func (_u *EvaluationGoalUpdateOne) SetNillableEvaluationID(v *uuid.UUID) *EvaluationGoalUpdateOne {
	if v != nil {
		_u.SetEvaluationID(*v)
	}
	return _u
}

// SetGoalID sets the "goal_id" field.
func (_u *EvaluationGoalUpdateOne) SetGoalID(v uuid.UUID) *EvaluationGoalUpdateOne {
	_u.mutation.SetGoalID(v)
	return _u
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (_u *EvaluationGoalUpdateOne) SetNillableGoalID(v *uuid.UUID) *EvaluationGoalUpdateOne {
	if v != nil {
		_u.SetGoalID(*v)
	}
	return _u
}

// SetEvaluation sets the "evaluation" edge to the Evaluation entity.
func (_u *EvaluationGoalUpdateOne) SetEvaluation(v *Evaluation) *EvaluationGoalUpdateOne {
	return _u.SetEvaluationID(v.ID)
}

// SetGoal sets the "goal" edge to the Goal entity.
func (_u *EvaluationGoalUpdateOne) SetGoal(v *Goal) *EvaluationGoalUpdateOne {
	return _u.SetGoalID(v.ID)
}

// Mutation returns the EvaluationGoalMutation object of the builder.
func (_u *EvaluationGoalUpdateOne) Mutation() *EvaluationGoalMutation {
	return _u.mutation
}

// ClearEvaluation clears the "evaluation" edge to the Evaluation entity.
func (_u *EvaluationGoalUpdateOne) ClearEvaluation() *EvaluationGoalUpdateOne {
	_u.mutation.ClearEvaluation()
	return _u
}

// ClearGoal clears the "goal" edge to the Goal entity.
func (_u *EvaluationGoalUpdateOne) ClearGoal() *EvaluationGoalUpdateOne {
	_u.mutation.ClearGoal()
	return _u
}

// Where appends a list predicates to the EvaluationGoalUpdate builder.
func (_u *EvaluationGoalUpdateOne) Where(ps ...predicate.EvaluationGoal) *EvaluationGoalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EvaluationGoalUpdateOne) Select(field string, fields ...string) *EvaluationGoalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EvaluationGoal entity.
func (_u *EvaluationGoalUpdateOne) Save(ctx context.Context) (*EvaluationGoal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EvaluationGoalUpdateOne) SaveX(ctx context.Context) *EvaluationGoal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EvaluationGoalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EvaluationGoalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EvaluationGoalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := evaluationgoal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EvaluationGoalUpdateOne) check() error {
	if v, ok := _u.mutation.FinalRating(); ok {
		if err := evaluationgoal.FinalRatingValidator(v); err != nil {
			return &ValidationError{Name: "final_rating", err: fmt.Errorf(`internal: validator failed for field "EvaluationGoal.final_rating": %w`, err)}
		}
	}
	if _u.mutation.EvaluationCleared() && len(_u.mutation.EvaluationIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "EvaluationGoal.evaluation"`)
	}
	if _u.mutation.GoalCleared() && len(_u.mutation.GoalIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "EvaluationGoal.goal"`)
	}
	return nil
}

func (_u *EvaluationGoalUpdateOne) sqlSave(ctx context.Context) (_node *EvaluationGoal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(evaluationgoal.Table, evaluationgoal.Columns, sqlgraph.NewFieldSpec(evaluationgoal.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`internal: missing "EvaluationGoal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evaluationgoal.FieldID)
		for _, f := range fields {
			if !evaluationgoal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
			}
			if f != evaluationgoal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(evaluationgoal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinalRating(); ok {
		_spec.SetField(evaluationgoal.FieldFinalRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFinalRating(); ok {
		_spec.AddField(evaluationgoal.FieldFinalRating, field.TypeInt, value)
	}
	if _u.mutation.FinalRatingCleared() {
		_spec.ClearField(evaluationgoal.FieldFinalRating, field.TypeInt)
	}
	if value, ok := _u.mutation.FinalComments(); ok {
		_spec.SetField(evaluationgoal.FieldFinalComments, field.TypeString, value)
	}
	if _u.mutation.FinalCommentsCleared() {
		_spec.ClearField(evaluationgoal.FieldFinalComments, field.TypeString)
	}
	if _u.mutation.EvaluationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationgoal.EvaluationTable,
			Columns: []string{evaluationgoal.EvaluationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EvaluationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationgoal.EvaluationTable,
			Columns: []string{evaluationgoal.EvaluationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evaluation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GoalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationgoal.GoalTable,
			Columns: []string{evaluationgoal.GoalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   evaluationgoal.GoalTable,
			Columns: []string{evaluationgoal.GoalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EvaluationGoal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{evaluationgoal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
