// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/competencyacceptancelevel"
	"github.com/sed-evaluacion-desempeno/api/internal/employee"
	"github.com/sed-evaluacion-desempeno/api/internal/evaluationcompetency"
	"github.com/sed-evaluacion-desempeno/api/internal/evaluationprofile"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// EvaluationProfileQuery is the builder for querying EvaluationProfile entities.
type EvaluationProfileQuery struct {
	config
	ctx                        *QueryContext
	order                      []evaluationprofile.OrderOption
	inters                     []Interceptor
	predicates                 []predicate.EvaluationProfile
	withEmployees              *EmployeeQuery
	withAcceptanceLevels       *CompetencyAcceptanceLevelQuery
	withEvaluationCompetencies *EvaluationCompetencyQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EvaluationProfileQuery builder.
func (_q *EvaluationProfileQuery) Where(ps ...predicate.EvaluationProfile) *EvaluationProfileQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EvaluationProfileQuery) Limit(limit int) *EvaluationProfileQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EvaluationProfileQuery) Offset(offset int) *EvaluationProfileQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EvaluationProfileQuery) Unique(unique bool) *EvaluationProfileQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EvaluationProfileQuery) Order(o ...evaluationprofile.OrderOption) *EvaluationProfileQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEmployees chains the current query on the "employees" edge.
func (_q *EvaluationProfileQuery) QueryEmployees() *EmployeeQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(evaluationprofile.Table, evaluationprofile.FieldID, selector),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, evaluationprofile.EmployeesTable, evaluationprofile.EmployeesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAcceptanceLevels chains the current query on the "acceptance_levels" edge.
func (_q *EvaluationProfileQuery) QueryAcceptanceLevels() *CompetencyAcceptanceLevelQuery {
	query := (&CompetencyAcceptanceLevelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(evaluationprofile.Table, evaluationprofile.FieldID, selector),
			sqlgraph.To(competencyacceptancelevel.Table, competencyacceptancelevel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, evaluationprofile.AcceptanceLevelsTable, evaluationprofile.AcceptanceLevelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvaluationCompetencies chains the current query on the "evaluation_competencies" edge.
func (_q *EvaluationProfileQuery) QueryEvaluationCompetencies() *EvaluationCompetencyQuery {
	query := (&EvaluationCompetencyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(evaluationprofile.Table, evaluationprofile.FieldID, selector),
			sqlgraph.To(evaluationcompetency.Table, evaluationcompetency.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, evaluationprofile.EvaluationCompetenciesTable, evaluationprofile.EvaluationCompetenciesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EvaluationProfile entity from the query.
// Returns a *NotFoundError when no EvaluationProfile was found.
func (_q *EvaluationProfileQuery) First(ctx context.Context) (*EvaluationProfile, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{evaluationprofile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EvaluationProfileQuery) FirstX(ctx context.Context) *EvaluationProfile {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EvaluationProfile ID from the query.
// Returns a *NotFoundError when no EvaluationProfile ID was found.
func (_q *EvaluationProfileQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{evaluationprofile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EvaluationProfileQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EvaluationProfile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EvaluationProfile entity is found.
// Returns a *NotFoundError when no EvaluationProfile entities are found.
func (_q *EvaluationProfileQuery) Only(ctx context.Context) (*EvaluationProfile, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{evaluationprofile.Label}
	default:
		return nil, &NotSingularError{evaluationprofile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EvaluationProfileQuery) OnlyX(ctx context.Context) *EvaluationProfile {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EvaluationProfile ID in the query.
// Returns a *NotSingularError when more than one EvaluationProfile ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EvaluationProfileQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{evaluationprofile.Label}
	default:
		err = &NotSingularError{evaluationprofile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EvaluationProfileQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EvaluationProfiles.
func (_q *EvaluationProfileQuery) All(ctx context.Context) ([]*EvaluationProfile, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EvaluationProfile, *EvaluationProfileQuery]()
	return withInterceptors[[]*EvaluationProfile](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EvaluationProfileQuery) AllX(ctx context.Context) []*EvaluationProfile {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EvaluationProfile IDs.
func (_q *EvaluationProfileQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(evaluationprofile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EvaluationProfileQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EvaluationProfileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EvaluationProfileQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EvaluationProfileQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EvaluationProfileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("internal: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EvaluationProfileQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EvaluationProfileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EvaluationProfileQuery) Clone() *EvaluationProfileQuery {
	if _q == nil {
		return nil
	}
	return &EvaluationProfileQuery{
		config:                     _q.config,
		ctx:                        _q.ctx.Clone(),
		order:                      append([]evaluationprofile.OrderOption{}, _q.order...),
		inters:                     append([]Interceptor{}, _q.inters...),
		predicates:                 append([]predicate.EvaluationProfile{}, _q.predicates...),
		withEmployees:              _q.withEmployees.Clone(),
		withAcceptanceLevels:       _q.withAcceptanceLevels.Clone(),
		withEvaluationCompetencies: _q.withEvaluationCompetencies.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEmployees tells the query-builder to eager-load the nodes that are connected to
// the "employees" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EvaluationProfileQuery) WithEmployees(opts ...func(*EmployeeQuery)) *EvaluationProfileQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEmployees = query
	return _q
}

// WithAcceptanceLevels tells the query-builder to eager-load the nodes that are connected to
// the "acceptance_levels" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EvaluationProfileQuery) WithAcceptanceLevels(opts ...func(*CompetencyAcceptanceLevelQuery)) *EvaluationProfileQuery {
	query := (&CompetencyAcceptanceLevelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAcceptanceLevels = query
	return _q
}

// WithEvaluationCompetencies tells the query-builder to eager-load the nodes that are connected to
// the "evaluation_competencies" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EvaluationProfileQuery) WithEvaluationCompetencies(opts ...func(*EvaluationCompetencyQuery)) *EvaluationProfileQuery {
	query := (&EvaluationCompetencyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvaluationCompetencies = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EvaluationProfile.Query().
//		GroupBy(evaluationprofile.FieldName).
//		Aggregate(internal.Count()).
//		Scan(ctx, &v)
func (_q *EvaluationProfileQuery) GroupBy(field string, fields ...string) *EvaluationProfileGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EvaluationProfileGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = evaluationprofile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.EvaluationProfile.Query().
//		Select(evaluationprofile.FieldName).
//		Scan(ctx, &v)
func (_q *EvaluationProfileQuery) Select(fields ...string) *EvaluationProfileSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EvaluationProfileSelect{EvaluationProfileQuery: _q}
	sbuild.label = evaluationprofile.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EvaluationProfileSelect configured with the given aggregations.
func (_q *EvaluationProfileQuery) Aggregate(fns ...AggregateFunc) *EvaluationProfileSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EvaluationProfileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("internal: uninitialized interceptor (forgotten import internal/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !evaluationprofile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EvaluationProfileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EvaluationProfile, error) {
	var (
		nodes       = []*EvaluationProfile{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withEmployees != nil,
			_q.withAcceptanceLevels != nil,
			_q.withEvaluationCompetencies != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EvaluationProfile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EvaluationProfile{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEmployees; query != nil {
		if err := _q.loadEmployees(ctx, query, nodes,
			func(n *EvaluationProfile) { n.Edges.Employees = []*Employee{} },
			func(n *EvaluationProfile, e *Employee) { n.Edges.Employees = append(n.Edges.Employees, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAcceptanceLevels; query != nil {
		if err := _q.loadAcceptanceLevels(ctx, query, nodes,
			func(n *EvaluationProfile) { n.Edges.AcceptanceLevels = []*CompetencyAcceptanceLevel{} },
			func(n *EvaluationProfile, e *CompetencyAcceptanceLevel) {
				n.Edges.AcceptanceLevels = append(n.Edges.AcceptanceLevels, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvaluationCompetencies; query != nil {
		if err := _q.loadEvaluationCompetencies(ctx, query, nodes,
			func(n *EvaluationProfile) { n.Edges.EvaluationCompetencies = []*EvaluationCompetency{} },
			func(n *EvaluationProfile, e *EvaluationCompetency) {
				n.Edges.EvaluationCompetencies = append(n.Edges.EvaluationCompetencies, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EvaluationProfileQuery) loadEmployees(ctx context.Context, query *EmployeeQuery, nodes []*EvaluationProfile, init func(*EvaluationProfile), assign func(*EvaluationProfile, *Employee)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*EvaluationProfile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(employee.FieldProfileID)
	}
	query.Where(predicate.Employee(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(evaluationprofile.EmployeesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProfileID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "profile_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EvaluationProfileQuery) loadAcceptanceLevels(ctx context.Context, query *CompetencyAcceptanceLevelQuery, nodes []*EvaluationProfile, init func(*EvaluationProfile), assign func(*EvaluationProfile, *CompetencyAcceptanceLevel)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*EvaluationProfile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(competencyacceptancelevel.FieldProfileID)
	}
	query.Where(predicate.CompetencyAcceptanceLevel(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(evaluationprofile.AcceptanceLevelsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProfileID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "profile_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EvaluationProfileQuery) loadEvaluationCompetencies(ctx context.Context, query *EvaluationCompetencyQuery, nodes []*EvaluationProfile, init func(*EvaluationProfile), assign func(*EvaluationProfile, *EvaluationCompetency)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*EvaluationProfile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(evaluationcompetency.FieldProfileID)
	}
	query.Where(predicate.EvaluationCompetency(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(evaluationprofile.EvaluationCompetenciesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProfileID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "profile_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *EvaluationProfileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EvaluationProfileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(evaluationprofile.Table, evaluationprofile.Columns, sqlgraph.NewFieldSpec(evaluationprofile.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evaluationprofile.FieldID)
		for i := range fields {
			if fields[i] != evaluationprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EvaluationProfileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(evaluationprofile.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = evaluationprofile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EvaluationProfileGroupBy is the group-by builder for EvaluationProfile entities.
type EvaluationProfileGroupBy struct {
	selector
	build *EvaluationProfileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EvaluationProfileGroupBy) Aggregate(fns ...AggregateFunc) *EvaluationProfileGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EvaluationProfileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EvaluationProfileQuery, *EvaluationProfileGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EvaluationProfileGroupBy) sqlScan(ctx context.Context, root *EvaluationProfileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EvaluationProfileSelect is the builder for selecting fields of EvaluationProfile entities.
type EvaluationProfileSelect struct {
	*EvaluationProfileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EvaluationProfileSelect) Aggregate(fns ...AggregateFunc) *EvaluationProfileSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EvaluationProfileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EvaluationProfileQuery, *EvaluationProfileSelect](ctx, _s.EvaluationProfileQuery, _s, _s.inters, v)
}

func (_s *EvaluationProfileSelect) sqlScan(ctx context.Context, root *EvaluationProfileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
