// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/employee"
	"github.com/sed-evaluacion-desempeno/api/internal/globalgoalassignment"
	"github.com/sed-evaluacion-desempeno/api/internal/goal"
)

// GlobalGoalAssignmentCreate is the builder for creating a GlobalGoalAssignment entity.
type GlobalGoalAssignmentCreate struct {
	config
	mutation *GlobalGoalAssignmentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *GlobalGoalAssignmentCreate) SetCreatedAt(v time.Time) *GlobalGoalAssignmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GlobalGoalAssignmentCreate) SetNillableCreatedAt(v *time.Time) *GlobalGoalAssignmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GlobalGoalAssignmentCreate) SetUpdatedAt(v time.Time) *GlobalGoalAssignmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GlobalGoalAssignmentCreate) SetNillableUpdatedAt(v *time.Time) *GlobalGoalAssignmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGoalID sets the "goal_id" field.
func (_c *GlobalGoalAssignmentCreate) SetGoalID(v uuid.UUID) *GlobalGoalAssignmentCreate {
	_c.mutation.SetGoalID(v)
	return _c
}

// SetEmployeeID sets the "employee_id" field.
func (_c *GlobalGoalAssignmentCreate) SetEmployeeID(v uuid.UUID) *GlobalGoalAssignmentCreate {
	_c.mutation.SetEmployeeID(v)
	return _c
}

// SetWeight sets the "weight" field.
func (_c *GlobalGoalAssignmentCreate) SetWeight(v float64) *GlobalGoalAssignmentCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetTargetValue sets the "target_value" field.
func (_c *GlobalGoalAssignmentCreate) SetTargetValue(v float64) *GlobalGoalAssignmentCreate {
	_c.mutation.SetTargetValue(v)
	return _c
}

// SetBaselineValue sets the "baseline_value" field.
func (_c *GlobalGoalAssignmentCreate) SetBaselineValue(v float64) *GlobalGoalAssignmentCreate {
	_c.mutation.SetBaselineValue(v)
	return _c
}

// SetNillableBaselineValue sets the "baseline_value" field if the given value is not nil.
func (_c *GlobalGoalAssignmentCreate) SetNillableBaselineValue(v *float64) *GlobalGoalAssignmentCreate {
	if v != nil {
		_c.SetBaselineValue(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GlobalGoalAssignmentCreate) SetID(v uuid.UUID) *GlobalGoalAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GlobalGoalAssignmentCreate) SetNillableID(v *uuid.UUID) *GlobalGoalAssignmentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGoal sets the "goal" edge to the Goal entity.
func (_c *GlobalGoalAssignmentCreate) SetGoal(v *Goal) *GlobalGoalAssignmentCreate {
	return _c.SetGoalID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_c *GlobalGoalAssignmentCreate) SetEmployee(v *Employee) *GlobalGoalAssignmentCreate {
	return _c.SetEmployeeID(v.ID)
}

// Mutation returns the GlobalGoalAssignmentMutation object of the builder.
func (_c *GlobalGoalAssignmentCreate) Mutation() *GlobalGoalAssignmentMutation {
	return _c.mutation
}

// Save creates the GlobalGoalAssignment in the database.
func (_c *GlobalGoalAssignmentCreate) Save(ctx context.Context) (*GlobalGoalAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GlobalGoalAssignmentCreate) SaveX(ctx context.Context) *GlobalGoalAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GlobalGoalAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GlobalGoalAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GlobalGoalAssignmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := globalgoalassignment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := globalgoalassignment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := globalgoalassignment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GlobalGoalAssignmentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`internal: missing required field "GlobalGoalAssignment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`internal: missing required field "GlobalGoalAssignment.updated_at"`)}
	}
	if _, ok := _c.mutation.GoalID(); !ok {
		return &ValidationError{Name: "goal_id", err: errors.New(`internal: missing required field "GlobalGoalAssignment.goal_id"`)}
	}
	if _, ok := _c.mutation.EmployeeID(); !ok {
		return &ValidationError{Name: "employee_id", err: errors.New(`internal: missing required field "GlobalGoalAssignment.employee_id"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`internal: missing required field "GlobalGoalAssignment.weight"`)}
	}
	if v, ok := _c.mutation.Weight(); ok {
		if err := globalgoalassignment.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`internal: validator failed for field "GlobalGoalAssignment.weight": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetValue(); !ok {
		return &ValidationError{Name: "target_value", err: errors.New(`internal: missing required field "GlobalGoalAssignment.target_value"`)}
	}
	if v, ok := _c.mutation.TargetValue(); ok {
		if err := globalgoalassignment.TargetValueValidator(v); err != nil {
			return &ValidationError{Name: "target_value", err: fmt.Errorf(`internal: validator failed for field "GlobalGoalAssignment.target_value": %w`, err)}
		}
	}
	if len(_c.mutation.GoalIDs()) == 0 {
		return &ValidationError{Name: "goal", err: errors.New(`internal: missing required edge "GlobalGoalAssignment.goal"`)}
	}
	if len(_c.mutation.EmployeeIDs()) == 0 {
		return &ValidationError{Name: "employee", err: errors.New(`internal: missing required edge "GlobalGoalAssignment.employee"`)}
	}
	return nil
}

func (_c *GlobalGoalAssignmentCreate) sqlSave(ctx context.Context) (*GlobalGoalAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GlobalGoalAssignmentCreate) createSpec() (*GlobalGoalAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &GlobalGoalAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(globalgoalassignment.Table, sqlgraph.NewFieldSpec(globalgoalassignment.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(globalgoalassignment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(globalgoalassignment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(globalgoalassignment.FieldWeight, field.TypeFloat64, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.TargetValue(); ok {
		_spec.SetField(globalgoalassignment.FieldTargetValue, field.TypeFloat64, value)
		_node.TargetValue = value
	}
	if value, ok := _c.mutation.BaselineValue(); ok {
		_spec.SetField(globalgoalassignment.FieldBaselineValue, field.TypeFloat64, value)
		_node.BaselineValue = &value
	}
	if nodes := _c.mutation.GoalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   globalgoalassignment.GoalTable,
			Columns: []string{globalgoalassignment.GoalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GoalID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   globalgoalassignment.EmployeeTable,
			Columns: []string{globalgoalassignment.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmployeeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GlobalGoalAssignmentCreateBulk is the builder for creating many GlobalGoalAssignment entities in bulk.
type GlobalGoalAssignmentCreateBulk struct {
	config
	err      error
	builders []*GlobalGoalAssignmentCreate
}

// Save creates the GlobalGoalAssignment entities in the database.
func (_c *GlobalGoalAssignmentCreateBulk) Save(ctx context.Context) ([]*GlobalGoalAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GlobalGoalAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GlobalGoalAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GlobalGoalAssignmentCreateBulk) SaveX(ctx context.Context) []*GlobalGoalAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GlobalGoalAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GlobalGoalAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
