// Code generated by ent, DO NOT EDIT.

package internal

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/goaltemplate"
	"github.com/sed-evaluacion-desempeno/api/internal/goaltemplatekpilink"
	"github.com/sed-evaluacion-desempeno/api/internal/kpi"
)

// GoalTemplateKpiLink is the model entity for the GoalTemplateKpiLink schema.
type GoalTemplateKpiLink struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TemplateID holds the value of the "template_id" field.
	TemplateID uuid.UUID `json:"template_id,omitempty"`
	// KpiID holds the value of the "kpi_id" field.
	KpiID uuid.UUID `json:"kpi_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GoalTemplateKpiLinkQuery when eager-loading is set.
	Edges        GoalTemplateKpiLinkEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GoalTemplateKpiLinkEdges holds the relations/edges for other nodes in the graph.
type GoalTemplateKpiLinkEdges struct {
	// Template holds the value of the template edge.
	Template *GoalTemplate `json:"template,omitempty"`
	// Kpi holds the value of the kpi edge.
	Kpi *KPI `json:"kpi,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TemplateOrErr returns the Template value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoalTemplateKpiLinkEdges) TemplateOrErr() (*GoalTemplate, error) {
	if e.Template != nil {
		return e.Template, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: goaltemplate.Label}
	}
	return nil, &NotLoadedError{edge: "template"}
}

// KpiOrErr returns the Kpi value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoalTemplateKpiLinkEdges) KpiOrErr() (*KPI, error) {
	if e.Kpi != nil {
		return e.Kpi, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: kpi.Label}
	}
	return nil, &NotLoadedError{edge: "kpi"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GoalTemplateKpiLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case goaltemplatekpilink.FieldCreatedAt, goaltemplatekpilink.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case goaltemplatekpilink.FieldID, goaltemplatekpilink.FieldTemplateID, goaltemplatekpilink.FieldKpiID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GoalTemplateKpiLink fields.
func (_m *GoalTemplateKpiLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case goaltemplatekpilink.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case goaltemplatekpilink.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case goaltemplatekpilink.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case goaltemplatekpilink.FieldTemplateID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value != nil {
				_m.TemplateID = *value
			}
		case goaltemplatekpilink.FieldKpiID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field kpi_id", values[i])
			} else if value != nil {
				_m.KpiID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GoalTemplateKpiLink.
// This includes values selected through modifiers, order, etc.
func (_m *GoalTemplateKpiLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTemplate queries the "template" edge of the GoalTemplateKpiLink entity.
func (_m *GoalTemplateKpiLink) QueryTemplate() *GoalTemplateQuery {
	return NewGoalTemplateKpiLinkClient(_m.config).QueryTemplate(_m)
}

// QueryKpi queries the "kpi" edge of the GoalTemplateKpiLink entity.
func (_m *GoalTemplateKpiLink) QueryKpi() *KPIQuery {
	return NewGoalTemplateKpiLinkClient(_m.config).QueryKpi(_m)
}

// Update returns a builder for updating this GoalTemplateKpiLink.
// Note that you need to call GoalTemplateKpiLink.Unwrap() before calling this method if this GoalTemplateKpiLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GoalTemplateKpiLink) Update() *GoalTemplateKpiLinkUpdateOne {
	return NewGoalTemplateKpiLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GoalTemplateKpiLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GoalTemplateKpiLink) Unwrap() *GoalTemplateKpiLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("internal: GoalTemplateKpiLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GoalTemplateKpiLink) String() string {
	var builder strings.Builder
	builder.WriteString("GoalTemplateKpiLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateID))
	builder.WriteString(", ")
	builder.WriteString("kpi_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.KpiID))
	builder.WriteByte(')')
	return builder.String()
}

// GoalTemplateKpiLinks is a parsable slice of GoalTemplateKpiLink.
type GoalTemplateKpiLinks []*GoalTemplateKpiLink
