// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/cycle"
	"github.com/sed-evaluacion-desempeno/api/internal/employee"
	"github.com/sed-evaluacion-desempeno/api/internal/goalassignment"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// GoalAssignmentQuery is the builder for querying GoalAssignment entities.
type GoalAssignmentQuery struct {
	config
	ctx          *QueryContext
	order        []goalassignment.OrderOption
	inters       []Interceptor
	predicates   []predicate.GoalAssignment
	withEmployee *EmployeeQuery
	withCycle    *CycleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GoalAssignmentQuery builder.
func (_q *GoalAssignmentQuery) Where(ps ...predicate.GoalAssignment) *GoalAssignmentQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GoalAssignmentQuery) Limit(limit int) *GoalAssignmentQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GoalAssignmentQuery) Offset(offset int) *GoalAssignmentQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GoalAssignmentQuery) Unique(unique bool) *GoalAssignmentQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GoalAssignmentQuery) Order(o ...goalassignment.OrderOption) *GoalAssignmentQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEmployee chains the current query on the "employee" edge.
func (_q *GoalAssignmentQuery) QueryEmployee() *EmployeeQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goalassignment.Table, goalassignment.FieldID, selector),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, goalassignment.EmployeeTable, goalassignment.EmployeeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCycle chains the current query on the "cycle" edge.
func (_q *GoalAssignmentQuery) QueryCycle() *CycleQuery {
	query := (&CycleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goalassignment.Table, goalassignment.FieldID, selector),
			sqlgraph.To(cycle.Table, cycle.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, goalassignment.CycleTable, goalassignment.CycleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GoalAssignment entity from the query.
// Returns a *NotFoundError when no GoalAssignment was found.
func (_q *GoalAssignmentQuery) First(ctx context.Context) (*GoalAssignment, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{goalassignment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GoalAssignmentQuery) FirstX(ctx context.Context) *GoalAssignment {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GoalAssignment ID from the query.
// Returns a *NotFoundError when no GoalAssignment ID was found.
func (_q *GoalAssignmentQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{goalassignment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GoalAssignmentQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GoalAssignment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GoalAssignment entity is found.
// Returns a *NotFoundError when no GoalAssignment entities are found.
func (_q *GoalAssignmentQuery) Only(ctx context.Context) (*GoalAssignment, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{goalassignment.Label}
	default:
		return nil, &NotSingularError{goalassignment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GoalAssignmentQuery) OnlyX(ctx context.Context) *GoalAssignment {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GoalAssignment ID in the query.
// Returns a *NotSingularError when more than one GoalAssignment ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GoalAssignmentQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{goalassignment.Label}
	default:
		err = &NotSingularError{goalassignment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GoalAssignmentQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GoalAssignments.
func (_q *GoalAssignmentQuery) All(ctx context.Context) ([]*GoalAssignment, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GoalAssignment, *GoalAssignmentQuery]()
	return withInterceptors[[]*GoalAssignment](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GoalAssignmentQuery) AllX(ctx context.Context) []*GoalAssignment {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GoalAssignment IDs.
func (_q *GoalAssignmentQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(goalassignment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GoalAssignmentQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GoalAssignmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GoalAssignmentQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GoalAssignmentQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GoalAssignmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("internal: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GoalAssignmentQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GoalAssignmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GoalAssignmentQuery) Clone() *GoalAssignmentQuery {
	if _q == nil {
		return nil
	}
	return &GoalAssignmentQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]goalassignment.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.GoalAssignment{}, _q.predicates...),
		withEmployee: _q.withEmployee.Clone(),
		withCycle:    _q.withCycle.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEmployee tells the query-builder to eager-load the nodes that are connected to
// the "employee" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GoalAssignmentQuery) WithEmployee(opts ...func(*EmployeeQuery)) *GoalAssignmentQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEmployee = query
	return _q
}

// WithCycle tells the query-builder to eager-load the nodes that are connected to
// the "cycle" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GoalAssignmentQuery) WithCycle(opts ...func(*CycleQuery)) *GoalAssignmentQuery {
	query := (&CycleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCycle = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GoalAssignment.Query().
//		GroupBy(goalassignment.FieldCreatedAt).
//		Aggregate(internal.Count()).
//		Scan(ctx, &v)
func (_q *GoalAssignmentQuery) GroupBy(field string, fields ...string) *GoalAssignmentGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GoalAssignmentGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = goalassignment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.GoalAssignment.Query().
//		Select(goalassignment.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *GoalAssignmentQuery) Select(fields ...string) *GoalAssignmentSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GoalAssignmentSelect{GoalAssignmentQuery: _q}
	sbuild.label = goalassignment.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GoalAssignmentSelect configured with the given aggregations.
func (_q *GoalAssignmentQuery) Aggregate(fns ...AggregateFunc) *GoalAssignmentSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GoalAssignmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("internal: uninitialized interceptor (forgotten import internal/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !goalassignment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GoalAssignmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GoalAssignment, error) {
	var (
		nodes       = []*GoalAssignment{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withEmployee != nil,
			_q.withCycle != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GoalAssignment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GoalAssignment{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEmployee; query != nil {
		if err := _q.loadEmployee(ctx, query, nodes, nil,
			func(n *GoalAssignment, e *Employee) { n.Edges.Employee = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCycle; query != nil {
		if err := _q.loadCycle(ctx, query, nodes, nil,
			func(n *GoalAssignment, e *Cycle) { n.Edges.Cycle = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GoalAssignmentQuery) loadEmployee(ctx context.Context, query *EmployeeQuery, nodes []*GoalAssignment, init func(*GoalAssignment), assign func(*GoalAssignment, *Employee)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GoalAssignment)
	for i := range nodes {
		fk := nodes[i].EmployeeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(employee.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "employee_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GoalAssignmentQuery) loadCycle(ctx context.Context, query *CycleQuery, nodes []*GoalAssignment, init func(*GoalAssignment), assign func(*GoalAssignment, *Cycle)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GoalAssignment)
	for i := range nodes {
		fk := nodes[i].CycleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(cycle.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "cycle_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *GoalAssignmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GoalAssignmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(goalassignment.Table, goalassignment.Columns, sqlgraph.NewFieldSpec(goalassignment.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goalassignment.FieldID)
		for i := range fields {
			if fields[i] != goalassignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withEmployee != nil {
			_spec.Node.AddColumnOnce(goalassignment.FieldEmployeeID)
		}
		if _q.withCycle != nil {
			_spec.Node.AddColumnOnce(goalassignment.FieldCycleID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GoalAssignmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(goalassignment.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = goalassignment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GoalAssignmentGroupBy is the group-by builder for GoalAssignment entities.
type GoalAssignmentGroupBy struct {
	selector
	build *GoalAssignmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GoalAssignmentGroupBy) Aggregate(fns ...AggregateFunc) *GoalAssignmentGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GoalAssignmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoalAssignmentQuery, *GoalAssignmentGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GoalAssignmentGroupBy) sqlScan(ctx context.Context, root *GoalAssignmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GoalAssignmentSelect is the builder for selecting fields of GoalAssignment entities.
type GoalAssignmentSelect struct {
	*GoalAssignmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GoalAssignmentSelect) Aggregate(fns ...AggregateFunc) *GoalAssignmentSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GoalAssignmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoalAssignmentQuery, *GoalAssignmentSelect](ctx, _s.GoalAssignmentQuery, _s, _s.inters, v)
}

func (_s *GoalAssignmentSelect) sqlScan(ctx context.Context, root *GoalAssignmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
