// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/employee"
	"github.com/sed-evaluacion-desempeno/api/internal/goal"
	"github.com/sed-evaluacion-desempeno/api/internal/goalcategory"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// GoalCategoryQuery is the builder for querying GoalCategory entities.
type GoalCategoryQuery struct {
	config
	ctx          *QueryContext
	order        []goalcategory.OrderOption
	inters       []Interceptor
	predicates   []predicate.GoalCategory
	withEmployee *EmployeeQuery
	withGoals    *GoalQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GoalCategoryQuery builder.
func (_q *GoalCategoryQuery) Where(ps ...predicate.GoalCategory) *GoalCategoryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GoalCategoryQuery) Limit(limit int) *GoalCategoryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GoalCategoryQuery) Offset(offset int) *GoalCategoryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GoalCategoryQuery) Unique(unique bool) *GoalCategoryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GoalCategoryQuery) Order(o ...goalcategory.OrderOption) *GoalCategoryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEmployee chains the current query on the "employee" edge.
func (_q *GoalCategoryQuery) QueryEmployee() *EmployeeQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goalcategory.Table, goalcategory.FieldID, selector),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, goalcategory.EmployeeTable, goalcategory.EmployeeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGoals chains the current query on the "goals" edge.
func (_q *GoalCategoryQuery) QueryGoals() *GoalQuery {
	query := (&GoalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goalcategory.Table, goalcategory.FieldID, selector),
			sqlgraph.To(goal.Table, goal.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, goalcategory.GoalsTable, goalcategory.GoalsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GoalCategory entity from the query.
// Returns a *NotFoundError when no GoalCategory was found.
func (_q *GoalCategoryQuery) First(ctx context.Context) (*GoalCategory, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{goalcategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GoalCategoryQuery) FirstX(ctx context.Context) *GoalCategory {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GoalCategory ID from the query.
// Returns a *NotFoundError when no GoalCategory ID was found.
func (_q *GoalCategoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{goalcategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GoalCategoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GoalCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GoalCategory entity is found.
// Returns a *NotFoundError when no GoalCategory entities are found.
func (_q *GoalCategoryQuery) Only(ctx context.Context) (*GoalCategory, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{goalcategory.Label}
	default:
		return nil, &NotSingularError{goalcategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GoalCategoryQuery) OnlyX(ctx context.Context) *GoalCategory {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GoalCategory ID in the query.
// Returns a *NotSingularError when more than one GoalCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GoalCategoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{goalcategory.Label}
	default:
		err = &NotSingularError{goalcategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GoalCategoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GoalCategories.
func (_q *GoalCategoryQuery) All(ctx context.Context) ([]*GoalCategory, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GoalCategory, *GoalCategoryQuery]()
	return withInterceptors[[]*GoalCategory](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GoalCategoryQuery) AllX(ctx context.Context) []*GoalCategory {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GoalCategory IDs.
func (_q *GoalCategoryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(goalcategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GoalCategoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GoalCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GoalCategoryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GoalCategoryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GoalCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("internal: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GoalCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GoalCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GoalCategoryQuery) Clone() *GoalCategoryQuery {
	if _q == nil {
		return nil
	}
	return &GoalCategoryQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]goalcategory.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.GoalCategory{}, _q.predicates...),
		withEmployee: _q.withEmployee.Clone(),
		withGoals:    _q.withGoals.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEmployee tells the query-builder to eager-load the nodes that are connected to
// the "employee" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GoalCategoryQuery) WithEmployee(opts ...func(*EmployeeQuery)) *GoalCategoryQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEmployee = query
	return _q
}

// WithGoals tells the query-builder to eager-load the nodes that are connected to
// the "goals" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GoalCategoryQuery) WithGoals(opts ...func(*GoalQuery)) *GoalCategoryQuery {
	query := (&GoalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGoals = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GoalCategory.Query().
//		GroupBy(goalcategory.FieldCreatedAt).
//		Aggregate(internal.Count()).
//		Scan(ctx, &v)
func (_q *GoalCategoryQuery) GroupBy(field string, fields ...string) *GoalCategoryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GoalCategoryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = goalcategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.GoalCategory.Query().
//		Select(goalcategory.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *GoalCategoryQuery) Select(fields ...string) *GoalCategorySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GoalCategorySelect{GoalCategoryQuery: _q}
	sbuild.label = goalcategory.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GoalCategorySelect configured with the given aggregations.
func (_q *GoalCategoryQuery) Aggregate(fns ...AggregateFunc) *GoalCategorySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GoalCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("internal: uninitialized interceptor (forgotten import internal/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !goalcategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GoalCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GoalCategory, error) {
	var (
		nodes       = []*GoalCategory{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withEmployee != nil,
			_q.withGoals != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GoalCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GoalCategory{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEmployee; query != nil {
		if err := _q.loadEmployee(ctx, query, nodes, nil,
			func(n *GoalCategory, e *Employee) { n.Edges.Employee = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGoals; query != nil {
		if err := _q.loadGoals(ctx, query, nodes,
			func(n *GoalCategory) { n.Edges.Goals = []*Goal{} },
			func(n *GoalCategory, e *Goal) { n.Edges.Goals = append(n.Edges.Goals, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GoalCategoryQuery) loadEmployee(ctx context.Context, query *EmployeeQuery, nodes []*GoalCategory, init func(*GoalCategory), assign func(*GoalCategory, *Employee)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GoalCategory)
	for i := range nodes {
		fk := nodes[i].EmployeeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(employee.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "employee_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GoalCategoryQuery) loadGoals(ctx context.Context, query *GoalQuery, nodes []*GoalCategory, init func(*GoalCategory), assign func(*GoalCategory, *Goal)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*GoalCategory)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(goal.FieldCategoryID)
	}
	query.Where(predicate.Goal(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(goalcategory.GoalsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CategoryID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "category_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *GoalCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GoalCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(goalcategory.Table, goalcategory.Columns, sqlgraph.NewFieldSpec(goalcategory.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goalcategory.FieldID)
		for i := range fields {
			if fields[i] != goalcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withEmployee != nil {
			_spec.Node.AddColumnOnce(goalcategory.FieldEmployeeID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GoalCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(goalcategory.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = goalcategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GoalCategoryGroupBy is the group-by builder for GoalCategory entities.
type GoalCategoryGroupBy struct {
	selector
	build *GoalCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GoalCategoryGroupBy) Aggregate(fns ...AggregateFunc) *GoalCategoryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GoalCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoalCategoryQuery, *GoalCategoryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GoalCategoryGroupBy) sqlScan(ctx context.Context, root *GoalCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GoalCategorySelect is the builder for selecting fields of GoalCategory entities.
type GoalCategorySelect struct {
	*GoalCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GoalCategorySelect) Aggregate(fns ...AggregateFunc) *GoalCategorySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GoalCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoalCategoryQuery, *GoalCategorySelect](ctx, _s.GoalCategoryQuery, _s, _s.inters, v)
}

func (_s *GoalCategorySelect) sqlScan(ctx context.Context, root *GoalCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
