// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/cycle"
	"github.com/sed-evaluacion-desempeno/api/internal/employee"
	"github.com/sed-evaluacion-desempeno/api/internal/goalassignment"
)

// GoalAssignmentCreate is the builder for creating a GoalAssignment entity.
type GoalAssignmentCreate struct {
	config
	mutation *GoalAssignmentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *GoalAssignmentCreate) SetCreatedAt(v time.Time) *GoalAssignmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GoalAssignmentCreate) SetNillableCreatedAt(v *time.Time) *GoalAssignmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GoalAssignmentCreate) SetUpdatedAt(v time.Time) *GoalAssignmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GoalAssignmentCreate) SetNillableUpdatedAt(v *time.Time) *GoalAssignmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEmployeeID sets the "employee_id" field.
func (_c *GoalAssignmentCreate) SetEmployeeID(v uuid.UUID) *GoalAssignmentCreate {
	_c.mutation.SetEmployeeID(v)
	return _c
}

// SetCycleID sets the "cycle_id" field.
func (_c *GoalAssignmentCreate) SetCycleID(v uuid.UUID) *GoalAssignmentCreate {
	_c.mutation.SetCycleID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *GoalAssignmentCreate) SetID(v uuid.UUID) *GoalAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GoalAssignmentCreate) SetNillableID(v *uuid.UUID) *GoalAssignmentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_c *GoalAssignmentCreate) SetEmployee(v *Employee) *GoalAssignmentCreate {
	return _c.SetEmployeeID(v.ID)
}

// SetCycle sets the "cycle" edge to the Cycle entity.
func (_c *GoalAssignmentCreate) SetCycle(v *Cycle) *GoalAssignmentCreate {
	return _c.SetCycleID(v.ID)
}

// Mutation returns the GoalAssignmentMutation object of the builder.
func (_c *GoalAssignmentCreate) Mutation() *GoalAssignmentMutation {
	return _c.mutation
}

// Save creates the GoalAssignment in the database.
func (_c *GoalAssignmentCreate) Save(ctx context.Context) (*GoalAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GoalAssignmentCreate) SaveX(ctx context.Context) *GoalAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoalAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoalAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GoalAssignmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := goalassignment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := goalassignment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := goalassignment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GoalAssignmentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`internal: missing required field "GoalAssignment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`internal: missing required field "GoalAssignment.updated_at"`)}
	}
	if _, ok := _c.mutation.EmployeeID(); !ok {
		return &ValidationError{Name: "employee_id", err: errors.New(`internal: missing required field "GoalAssignment.employee_id"`)}
	}
	if _, ok := _c.mutation.CycleID(); !ok {
		return &ValidationError{Name: "cycle_id", err: errors.New(`internal: missing required field "GoalAssignment.cycle_id"`)}
	}
	if len(_c.mutation.EmployeeIDs()) == 0 {
		return &ValidationError{Name: "employee", err: errors.New(`internal: missing required edge "GoalAssignment.employee"`)}
	}
	if len(_c.mutation.CycleIDs()) == 0 {
		return &ValidationError{Name: "cycle", err: errors.New(`internal: missing required edge "GoalAssignment.cycle"`)}
	}
	return nil
}

func (_c *GoalAssignmentCreate) sqlSave(ctx context.Context) (*GoalAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GoalAssignmentCreate) createSpec() (*GoalAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &GoalAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(goalassignment.Table, sqlgraph.NewFieldSpec(goalassignment.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(goalassignment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(goalassignment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goalassignment.EmployeeTable,
			Columns: []string{goalassignment.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmployeeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CycleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goalassignment.CycleTable,
			Columns: []string{goalassignment.CycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cycle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CycleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GoalAssignmentCreateBulk is the builder for creating many GoalAssignment entities in bulk.
type GoalAssignmentCreateBulk struct {
	config
	err      error
	builders []*GoalAssignmentCreate
}

// Save creates the GoalAssignment entities in the database.
func (_c *GoalAssignmentCreateBulk) Save(ctx context.Context) ([]*GoalAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GoalAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoalAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GoalAssignmentCreateBulk) SaveX(ctx context.Context) []*GoalAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoalAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoalAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
