// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/goaltemplate"
	"github.com/sed-evaluacion-desempeno/api/internal/goaltemplatekpilink"
	"github.com/sed-evaluacion-desempeno/api/internal/kpi"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// GoalTemplateKpiLinkUpdate is the builder for updating GoalTemplateKpiLink entities.
type GoalTemplateKpiLinkUpdate struct {
	config
	hooks    []Hook
	mutation *GoalTemplateKpiLinkMutation
}

// Where appends a list predicates to the GoalTemplateKpiLinkUpdate builder.
func (_u *GoalTemplateKpiLinkUpdate) Where(ps ...predicate.GoalTemplateKpiLink) *GoalTemplateKpiLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GoalTemplateKpiLinkUpdate) SetUpdatedAt(v time.Time) *GoalTemplateKpiLinkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *GoalTemplateKpiLinkUpdate) SetTemplateID(v uuid.UUID) *GoalTemplateKpiLinkUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *GoalTemplateKpiLinkUpdate) SetNillableTemplateID(v *uuid.UUID) *GoalTemplateKpiLinkUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetKpiID sets the "kpi_id" field.
func (_u *GoalTemplateKpiLinkUpdate) SetKpiID(v uuid.UUID) *GoalTemplateKpiLinkUpdate {
	_u.mutation.SetKpiID(v)
	return _u
}

// SetNillableKpiID sets the "kpi_id" field if the given value is not nil.
func (_u *GoalTemplateKpiLinkUpdate) SetNillableKpiID(v *uuid.UUID) *GoalTemplateKpiLinkUpdate {
	if v != nil {
		_u.SetKpiID(*v)
	}
	return _u
}

// SetTemplate sets the "template" edge to the GoalTemplate entity.
func (_u *GoalTemplateKpiLinkUpdate) SetTemplate(v *GoalTemplate) *GoalTemplateKpiLinkUpdate {
	return _u.SetTemplateID(v.ID)
}

// SetKpi sets the "kpi" edge to the KPI entity.
func (_u *GoalTemplateKpiLinkUpdate) SetKpi(v *KPI) *GoalTemplateKpiLinkUpdate {
	return _u.SetKpiID(v.ID)
}

// Mutation returns the GoalTemplateKpiLinkMutation object of the builder.
func (_u *GoalTemplateKpiLinkUpdate) Mutation() *GoalTemplateKpiLinkMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the GoalTemplate entity.
func (_u *GoalTemplateKpiLinkUpdate) ClearTemplate() *GoalTemplateKpiLinkUpdate {
	_u.mutation.ClearTemplate()
	return _u
}

// ClearKpi clears the "kpi" edge to the KPI entity.
func (_u *GoalTemplateKpiLinkUpdate) ClearKpi() *GoalTemplateKpiLinkUpdate {
	_u.mutation.ClearKpi()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GoalTemplateKpiLinkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoalTemplateKpiLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GoalTemplateKpiLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoalTemplateKpiLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GoalTemplateKpiLinkUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := goaltemplatekpilink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GoalTemplateKpiLinkUpdate) check() error {
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "GoalTemplateKpiLink.template"`)
	}
	if _u.mutation.KpiCleared() && len(_u.mutation.KpiIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "GoalTemplateKpiLink.kpi"`)
	}
	return nil
}

func (_u *GoalTemplateKpiLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(goaltemplatekpilink.Table, goaltemplatekpilink.Columns, sqlgraph.NewFieldSpec(goaltemplatekpilink.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(goaltemplatekpilink.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goaltemplatekpilink.TemplateTable,
			Columns: []string{goaltemplatekpilink.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goaltemplate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goaltemplatekpilink.TemplateTable,
			Columns: []string{goaltemplatekpilink.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goaltemplate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.KpiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goaltemplatekpilink.KpiTable,
			Columns: []string{goaltemplatekpilink.KpiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(kpi.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KpiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goaltemplatekpilink.KpiTable,
			Columns: []string{goaltemplatekpilink.KpiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(kpi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goaltemplatekpilink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GoalTemplateKpiLinkUpdateOne is the builder for updating a single GoalTemplateKpiLink entity.
type GoalTemplateKpiLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GoalTemplateKpiLinkMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GoalTemplateKpiLinkUpdateOne) SetUpdatedAt(v time.Time) *GoalTemplateKpiLinkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *GoalTemplateKpiLinkUpdateOne) SetTemplateID(v uuid.UUID) *GoalTemplateKpiLinkUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *GoalTemplateKpiLinkUpdateOne) SetNillableTemplateID(v *uuid.UUID) *GoalTemplateKpiLinkUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetKpiID sets the "kpi_id" field.
func (_u *GoalTemplateKpiLinkUpdateOne) SetKpiID(v uuid.UUID) *GoalTemplateKpiLinkUpdateOne {
	_u.mutation.SetKpiID(v)
	return _u
}

// SetNillableKpiID sets the "kpi_id" field if the given value is not nil.
func (_u *GoalTemplateKpiLinkUpdateOne) SetNillableKpiID(v *uuid.UUID) *GoalTemplateKpiLinkUpdateOne {
	if v != nil {
		_u.SetKpiID(*v)
	}
	return _u
}

// SetTemplate sets the "template" edge to the GoalTemplate entity.
func (_u *GoalTemplateKpiLinkUpdateOne) SetTemplate(v *GoalTemplate) *GoalTemplateKpiLinkUpdateOne {
	return _u.SetTemplateID(v.ID)
}

// SetKpi sets the "kpi" edge to the KPI entity.
func (_u *GoalTemplateKpiLinkUpdateOne) SetKpi(v *KPI) *GoalTemplateKpiLinkUpdateOne {
	return _u.SetKpiID(v.ID)
}

// Mutation returns the GoalTemplateKpiLinkMutation object of the builder.
func (_u *GoalTemplateKpiLinkUpdateOne) Mutation() *GoalTemplateKpiLinkMutation {
	return _u.mutation
}

// ClearTemplate clears the "template" edge to the GoalTemplate entity.
func (_u *GoalTemplateKpiLinkUpdateOne) ClearTemplate() *GoalTemplateKpiLinkUpdateOne {
	_u.mutation.ClearTemplate()
	return _u
}

// ClearKpi clears the "kpi" edge to the KPI entity.
func (_u *GoalTemplateKpiLinkUpdateOne) ClearKpi() *GoalTemplateKpiLinkUpdateOne {
	_u.mutation.ClearKpi()
	return _u
}

// Where appends a list predicates to the GoalTemplateKpiLinkUpdate builder.
func (_u *GoalTemplateKpiLinkUpdateOne) Where(ps ...predicate.GoalTemplateKpiLink) *GoalTemplateKpiLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GoalTemplateKpiLinkUpdateOne) Select(field string, fields ...string) *GoalTemplateKpiLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GoalTemplateKpiLink entity.
func (_u *GoalTemplateKpiLinkUpdateOne) Save(ctx context.Context) (*GoalTemplateKpiLink, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoalTemplateKpiLinkUpdateOne) SaveX(ctx context.Context) *GoalTemplateKpiLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GoalTemplateKpiLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoalTemplateKpiLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GoalTemplateKpiLinkUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := goaltemplatekpilink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GoalTemplateKpiLinkUpdateOne) check() error {
	if _u.mutation.TemplateCleared() && len(_u.mutation.TemplateIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "GoalTemplateKpiLink.template"`)
	}
	if _u.mutation.KpiCleared() && len(_u.mutation.KpiIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "GoalTemplateKpiLink.kpi"`)
	}
	return nil
}

func (_u *GoalTemplateKpiLinkUpdateOne) sqlSave(ctx context.Context) (_node *GoalTemplateKpiLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(goaltemplatekpilink.Table, goaltemplatekpilink.Columns, sqlgraph.NewFieldSpec(goaltemplatekpilink.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`internal: missing "GoalTemplateKpiLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goaltemplatekpilink.FieldID)
		for _, f := range fields {
			if !goaltemplatekpilink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
			}
			if f != goaltemplatekpilink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(goaltemplatekpilink.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TemplateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goaltemplatekpilink.TemplateTable,
			Columns: []string{goaltemplatekpilink.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goaltemplate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goaltemplatekpilink.TemplateTable,
			Columns: []string{goaltemplatekpilink.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goaltemplate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.KpiCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goaltemplatekpilink.KpiTable,
			Columns: []string{goaltemplatekpilink.KpiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(kpi.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KpiIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goaltemplatekpilink.KpiTable,
			Columns: []string{goaltemplatekpilink.KpiColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(kpi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GoalTemplateKpiLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goaltemplatekpilink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
