// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/goalcomment"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// GoalCommentUpdate is the builder for updating GoalComment entities.
type GoalCommentUpdate struct {
	config
	hooks    []Hook
	mutation *GoalCommentMutation
}

// Where appends a list predicates to the GoalCommentUpdate builder.
func (_u *GoalCommentUpdate) Where(ps ...predicate.GoalComment) *GoalCommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GoalCommentUpdate) SetUpdatedAt(v time.Time) *GoalCommentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGoalID sets the "goal_id" field.
func (_u *GoalCommentUpdate) SetGoalID(v uuid.UUID) *GoalCommentUpdate {
	_u.mutation.SetGoalID(v)
	return _u
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (_u *GoalCommentUpdate) SetNillableGoalID(v *uuid.UUID) *GoalCommentUpdate {
	if v != nil {
		_u.SetGoalID(*v)
	}
	return _u
}

// ClearGoalID clears the value of the "goal_id" field.
func (_u *GoalCommentUpdate) ClearGoalID() *GoalCommentUpdate {
	_u.mutation.ClearGoalID()
	return _u
}

// SetPhase sets the "phase" field.
func (_u *GoalCommentUpdate) SetPhase(v goalcomment.Phase) *GoalCommentUpdate {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *GoalCommentUpdate) SetNillablePhase(v *goalcomment.Phase) *GoalCommentUpdate {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// Mutation returns the GoalCommentMutation object of the builder.
func (_u *GoalCommentUpdate) Mutation() *GoalCommentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GoalCommentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoalCommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GoalCommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoalCommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GoalCommentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := goalcomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GoalCommentUpdate) check() error {
	if v, ok := _u.mutation.Phase(); ok {
		if err := goalcomment.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`internal: validator failed for field "GoalComment.phase": %w`, err)}
		}
	}
	return nil
}

func (_u *GoalCommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(goalcomment.Table, goalcomment.Columns, sqlgraph.NewFieldSpec(goalcomment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(goalcomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GoalID(); ok {
		_spec.SetField(goalcomment.FieldGoalID, field.TypeUUID, value)
	}
	if _u.mutation.GoalIDCleared() {
		_spec.ClearField(goalcomment.FieldGoalID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(goalcomment.FieldPhase, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goalcomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GoalCommentUpdateOne is the builder for updating a single GoalComment entity.
type GoalCommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GoalCommentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GoalCommentUpdateOne) SetUpdatedAt(v time.Time) *GoalCommentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGoalID sets the "goal_id" field.
func (_u *GoalCommentUpdateOne) SetGoalID(v uuid.UUID) *GoalCommentUpdateOne {
	_u.mutation.SetGoalID(v)
	return _u
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (_u *GoalCommentUpdateOne) SetNillableGoalID(v *uuid.UUID) *GoalCommentUpdateOne {
	if v != nil {
		_u.SetGoalID(*v)
	}
	return _u
}

// ClearGoalID clears the value of the "goal_id" field.
func (_u *GoalCommentUpdateOne) ClearGoalID() *GoalCommentUpdateOne {
	_u.mutation.ClearGoalID()
	return _u
}

// SetPhase sets the "phase" field.
func (_u *GoalCommentUpdateOne) SetPhase(v goalcomment.Phase) *GoalCommentUpdateOne {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *GoalCommentUpdateOne) SetNillablePhase(v *goalcomment.Phase) *GoalCommentUpdateOne {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// Mutation returns the GoalCommentMutation object of the builder.
func (_u *GoalCommentUpdateOne) Mutation() *GoalCommentMutation {
	return _u.mutation
}

// Where appends a list predicates to the GoalCommentUpdate builder.
func (_u *GoalCommentUpdateOne) Where(ps ...predicate.GoalComment) *GoalCommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GoalCommentUpdateOne) Select(field string, fields ...string) *GoalCommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GoalComment entity.
func (_u *GoalCommentUpdateOne) Save(ctx context.Context) (*GoalComment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoalCommentUpdateOne) SaveX(ctx context.Context) *GoalComment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GoalCommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoalCommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GoalCommentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := goalcomment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GoalCommentUpdateOne) check() error {
	if v, ok := _u.mutation.Phase(); ok {
		if err := goalcomment.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`internal: validator failed for field "GoalComment.phase": %w`, err)}
		}
	}
	return nil
}

func (_u *GoalCommentUpdateOne) sqlSave(ctx context.Context) (_node *GoalComment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(goalcomment.Table, goalcomment.Columns, sqlgraph.NewFieldSpec(goalcomment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`internal: missing "GoalComment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goalcomment.FieldID)
		for _, f := range fields {
			if !goalcomment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
			}
			if f != goalcomment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(goalcomment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GoalID(); ok {
		_spec.SetField(goalcomment.FieldGoalID, field.TypeUUID, value)
	}
	if _u.mutation.GoalIDCleared() {
		_spec.ClearField(goalcomment.FieldGoalID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(goalcomment.FieldPhase, field.TypeEnum, value)
	}
	_node = &GoalComment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goalcomment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
