// Code generated by ent, DO NOT EDIT.

package internal

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/goalcomment"
)

// GoalComment is the model entity for the GoalComment schema.
type GoalComment struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GoalID holds the value of the "goal_id" field.
	GoalID *uuid.UUID `json:"goal_id,omitempty"`
	// Phase holds the value of the "phase" field.
	Phase        goalcomment.Phase `json:"phase,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GoalComment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case goalcomment.FieldGoalID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case goalcomment.FieldPhase:
			values[i] = new(sql.NullString)
		case goalcomment.FieldCreatedAt, goalcomment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case goalcomment.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GoalComment fields.
func (_m *GoalComment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case goalcomment.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case goalcomment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case goalcomment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case goalcomment.FieldGoalID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field goal_id", values[i])
			} else if value.Valid {
				_m.GoalID = new(uuid.UUID)
				*_m.GoalID = *value.S.(*uuid.UUID)
			}
		case goalcomment.FieldPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phase", values[i])
			} else if value.Valid {
				_m.Phase = goalcomment.Phase(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GoalComment.
// This includes values selected through modifiers, order, etc.
func (_m *GoalComment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GoalComment.
// Note that you need to call GoalComment.Unwrap() before calling this method if this GoalComment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GoalComment) Update() *GoalCommentUpdateOne {
	return NewGoalCommentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GoalComment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GoalComment) Unwrap() *GoalComment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("internal: GoalComment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GoalComment) String() string {
	var builder strings.Builder
	builder.WriteString("GoalComment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.GoalID; v != nil {
		builder.WriteString("goal_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("phase=")
	builder.WriteString(fmt.Sprintf("%v", _m.Phase))
	builder.WriteByte(')')
	return builder.String()
}

// GoalComments is a parsable slice of GoalComment.
type GoalComments []*GoalComment
