// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/nineboxquadrant"
)

// NineBoxQuadrantCreate is the builder for creating a NineBoxQuadrant entity.
type NineBoxQuadrantCreate struct {
	config
	mutation *NineBoxQuadrantMutation
	hooks    []Hook
}

// SetQuadrant sets the "quadrant" field.
func (_c *NineBoxQuadrantCreate) SetQuadrant(v int) *NineBoxQuadrantCreate {
	_c.mutation.SetQuadrant(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *NineBoxQuadrantCreate) SetLabel(v string) *NineBoxQuadrantCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *NineBoxQuadrantCreate) SetDescription(v string) *NineBoxQuadrantCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *NineBoxQuadrantCreate) SetNillableDescription(v *string) *NineBoxQuadrantCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetColor sets the "color" field.
func (_c *NineBoxQuadrantCreate) SetColor(v string) *NineBoxQuadrantCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetActionRecommendation sets the "action_recommendation" field.
func (_c *NineBoxQuadrantCreate) SetActionRecommendation(v string) *NineBoxQuadrantCreate {
	_c.mutation.SetActionRecommendation(v)
	return _c
}

// SetNillableActionRecommendation sets the "action_recommendation" field if the given value is not nil.
func (_c *NineBoxQuadrantCreate) SetNillableActionRecommendation(v *string) *NineBoxQuadrantCreate {
	if v != nil {
		_c.SetActionRecommendation(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NineBoxQuadrantCreate) SetID(v uuid.UUID) *NineBoxQuadrantCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NineBoxQuadrantCreate) SetNillableID(v *uuid.UUID) *NineBoxQuadrantCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the NineBoxQuadrantMutation object of the builder.
func (_c *NineBoxQuadrantCreate) Mutation() *NineBoxQuadrantMutation {
	return _c.mutation
}

// Save creates the NineBoxQuadrant in the database.
func (_c *NineBoxQuadrantCreate) Save(ctx context.Context) (*NineBoxQuadrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NineBoxQuadrantCreate) SaveX(ctx context.Context) *NineBoxQuadrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NineBoxQuadrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NineBoxQuadrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NineBoxQuadrantCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := nineboxquadrant.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NineBoxQuadrantCreate) check() error {
	if _, ok := _c.mutation.Quadrant(); !ok {
		return &ValidationError{Name: "quadrant", err: errors.New(`internal: missing required field "NineBoxQuadrant.quadrant"`)}
	}
	if v, ok := _c.mutation.Quadrant(); ok {
		if err := nineboxquadrant.QuadrantValidator(v); err != nil {
			return &ValidationError{Name: "quadrant", err: fmt.Errorf(`internal: validator failed for field "NineBoxQuadrant.quadrant": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`internal: missing required field "NineBoxQuadrant.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := nineboxquadrant.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`internal: validator failed for field "NineBoxQuadrant.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`internal: missing required field "NineBoxQuadrant.color"`)}
	}
	if v, ok := _c.mutation.Color(); ok {
		if err := nineboxquadrant.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`internal: validator failed for field "NineBoxQuadrant.color": %w`, err)}
		}
	}
	return nil
}

func (_c *NineBoxQuadrantCreate) sqlSave(ctx context.Context) (*NineBoxQuadrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NineBoxQuadrantCreate) createSpec() (*NineBoxQuadrant, *sqlgraph.CreateSpec) {
	var (
		_node = &NineBoxQuadrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nineboxquadrant.Table, sqlgraph.NewFieldSpec(nineboxquadrant.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Quadrant(); ok {
		_spec.SetField(nineboxquadrant.FieldQuadrant, field.TypeInt, value)
		_node.Quadrant = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(nineboxquadrant.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(nineboxquadrant.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(nineboxquadrant.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := _c.mutation.ActionRecommendation(); ok {
		_spec.SetField(nineboxquadrant.FieldActionRecommendation, field.TypeString, value)
		_node.ActionRecommendation = value
	}
	return _node, _spec
}

// NineBoxQuadrantCreateBulk is the builder for creating many NineBoxQuadrant entities in bulk.
type NineBoxQuadrantCreateBulk struct {
	config
	err      error
	builders []*NineBoxQuadrantCreate
}

// Save creates the NineBoxQuadrant entities in the database.
func (_c *NineBoxQuadrantCreateBulk) Save(ctx context.Context) ([]*NineBoxQuadrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NineBoxQuadrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NineBoxQuadrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NineBoxQuadrantCreateBulk) SaveX(ctx context.Context) []*NineBoxQuadrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NineBoxQuadrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NineBoxQuadrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
