// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/employee"
	"github.com/sed-evaluacion-desempeno/api/internal/nineboxentry"
	"github.com/sed-evaluacion-desempeno/api/internal/nineboxmatrix"
)

// NineBoxEntryCreate is the builder for creating a NineBoxEntry entity.
type NineBoxEntryCreate struct {
	config
	mutation *NineBoxEntryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *NineBoxEntryCreate) SetCreatedAt(v time.Time) *NineBoxEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NineBoxEntryCreate) SetNillableCreatedAt(v *time.Time) *NineBoxEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NineBoxEntryCreate) SetUpdatedAt(v time.Time) *NineBoxEntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NineBoxEntryCreate) SetNillableUpdatedAt(v *time.Time) *NineBoxEntryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *NineBoxEntryCreate) SetCreatedBy(v uuid.UUID) *NineBoxEntryCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *NineBoxEntryCreate) SetUpdatedBy(v uuid.UUID) *NineBoxEntryCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetPerformanceScore sets the "performance_score" field.
func (_c *NineBoxEntryCreate) SetPerformanceScore(v int) *NineBoxEntryCreate {
	_c.mutation.SetPerformanceScore(v)
	return _c
}

// SetPotentialScore sets the "potential_score" field.
func (_c *NineBoxEntryCreate) SetPotentialScore(v int) *NineBoxEntryCreate {
	_c.mutation.SetPotentialScore(v)
	return _c
}

// SetQuadrant sets the "quadrant" field.
func (_c *NineBoxEntryCreate) SetQuadrant(v int) *NineBoxEntryCreate {
	_c.mutation.SetQuadrant(v)
	return _c
}

// SetComments sets the "comments" field.
func (_c *NineBoxEntryCreate) SetComments(v string) *NineBoxEntryCreate {
	_c.mutation.SetComments(v)
	return _c
}

// SetNillableComments sets the "comments" field if the given value is not nil.
func (_c *NineBoxEntryCreate) SetNillableComments(v *string) *NineBoxEntryCreate {
	if v != nil {
		_c.SetComments(*v)
	}
	return _c
}

// SetMatrixID sets the "matrix_id" field.
func (_c *NineBoxEntryCreate) SetMatrixID(v uuid.UUID) *NineBoxEntryCreate {
	_c.mutation.SetMatrixID(v)
	return _c
}

// SetEvaluateeID sets the "evaluatee_id" field.
func (_c *NineBoxEntryCreate) SetEvaluateeID(v uuid.UUID) *NineBoxEntryCreate {
	_c.mutation.SetEvaluateeID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *NineBoxEntryCreate) SetID(v uuid.UUID) *NineBoxEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NineBoxEntryCreate) SetNillableID(v *uuid.UUID) *NineBoxEntryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetMatrix sets the "matrix" edge to the NineBoxMatrix entity.
func (_c *NineBoxEntryCreate) SetMatrix(v *NineBoxMatrix) *NineBoxEntryCreate {
	return _c.SetMatrixID(v.ID)
}

// SetEvaluatee sets the "evaluatee" edge to the Employee entity.
func (_c *NineBoxEntryCreate) SetEvaluatee(v *Employee) *NineBoxEntryCreate {
	return _c.SetEvaluateeID(v.ID)
}

// Mutation returns the NineBoxEntryMutation object of the builder.
func (_c *NineBoxEntryCreate) Mutation() *NineBoxEntryMutation {
	return _c.mutation
}

// Save creates the NineBoxEntry in the database.
func (_c *NineBoxEntryCreate) Save(ctx context.Context) (*NineBoxEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NineBoxEntryCreate) SaveX(ctx context.Context) *NineBoxEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NineBoxEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NineBoxEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NineBoxEntryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := nineboxentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := nineboxentry.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := nineboxentry.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NineBoxEntryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`internal: missing required field "NineBoxEntry.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`internal: missing required field "NineBoxEntry.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`internal: missing required field "NineBoxEntry.created_by"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`internal: missing required field "NineBoxEntry.updated_by"`)}
	}
	if _, ok := _c.mutation.PerformanceScore(); !ok {
		return &ValidationError{Name: "performance_score", err: errors.New(`internal: missing required field "NineBoxEntry.performance_score"`)}
	}
	if v, ok := _c.mutation.PerformanceScore(); ok {
		if err := nineboxentry.PerformanceScoreValidator(v); err != nil {
			return &ValidationError{Name: "performance_score", err: fmt.Errorf(`internal: validator failed for field "NineBoxEntry.performance_score": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PotentialScore(); !ok {
		return &ValidationError{Name: "potential_score", err: errors.New(`internal: missing required field "NineBoxEntry.potential_score"`)}
	}
	if v, ok := _c.mutation.PotentialScore(); ok {
		if err := nineboxentry.PotentialScoreValidator(v); err != nil {
			return &ValidationError{Name: "potential_score", err: fmt.Errorf(`internal: validator failed for field "NineBoxEntry.potential_score": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quadrant(); !ok {
		return &ValidationError{Name: "quadrant", err: errors.New(`internal: missing required field "NineBoxEntry.quadrant"`)}
	}
	if v, ok := _c.mutation.Quadrant(); ok {
		if err := nineboxentry.QuadrantValidator(v); err != nil {
			return &ValidationError{Name: "quadrant", err: fmt.Errorf(`internal: validator failed for field "NineBoxEntry.quadrant": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MatrixID(); !ok {
		return &ValidationError{Name: "matrix_id", err: errors.New(`internal: missing required field "NineBoxEntry.matrix_id"`)}
	}
	if _, ok := _c.mutation.EvaluateeID(); !ok {
		return &ValidationError{Name: "evaluatee_id", err: errors.New(`internal: missing required field "NineBoxEntry.evaluatee_id"`)}
	}
	if len(_c.mutation.MatrixIDs()) == 0 {
		return &ValidationError{Name: "matrix", err: errors.New(`internal: missing required edge "NineBoxEntry.matrix"`)}
	}
	if len(_c.mutation.EvaluateeIDs()) == 0 {
		return &ValidationError{Name: "evaluatee", err: errors.New(`internal: missing required edge "NineBoxEntry.evaluatee"`)}
	}
	return nil
}

func (_c *NineBoxEntryCreate) sqlSave(ctx context.Context) (*NineBoxEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NineBoxEntryCreate) createSpec() (*NineBoxEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &NineBoxEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nineboxentry.Table, sqlgraph.NewFieldSpec(nineboxentry.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(nineboxentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(nineboxentry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(nineboxentry.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(nineboxentry.FieldUpdatedBy, field.TypeUUID, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.PerformanceScore(); ok {
		_spec.SetField(nineboxentry.FieldPerformanceScore, field.TypeInt, value)
		_node.PerformanceScore = value
	}
	if value, ok := _c.mutation.PotentialScore(); ok {
		_spec.SetField(nineboxentry.FieldPotentialScore, field.TypeInt, value)
		_node.PotentialScore = value
	}
	if value, ok := _c.mutation.Quadrant(); ok {
		_spec.SetField(nineboxentry.FieldQuadrant, field.TypeInt, value)
		_node.Quadrant = value
	}
	if value, ok := _c.mutation.Comments(); ok {
		_spec.SetField(nineboxentry.FieldComments, field.TypeString, value)
		_node.Comments = value
	}
	if nodes := _c.mutation.MatrixIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nineboxentry.MatrixTable,
			Columns: []string{nineboxentry.MatrixColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(nineboxmatrix.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MatrixID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EvaluateeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   nineboxentry.EvaluateeTable,
			Columns: []string{nineboxentry.EvaluateeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EvaluateeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NineBoxEntryCreateBulk is the builder for creating many NineBoxEntry entities in bulk.
type NineBoxEntryCreateBulk struct {
	config
	err      error
	builders []*NineBoxEntryCreate
}

// Save creates the NineBoxEntry entities in the database.
func (_c *NineBoxEntryCreateBulk) Save(ctx context.Context) ([]*NineBoxEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NineBoxEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NineBoxEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NineBoxEntryCreateBulk) SaveX(ctx context.Context) []*NineBoxEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NineBoxEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NineBoxEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
