// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sed-evaluacion-desempeno/api/internal/nineboxentry"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// NineBoxEntryDelete is the builder for deleting a NineBoxEntry entity.
type NineBoxEntryDelete struct {
	config
	hooks    []Hook
	mutation *NineBoxEntryMutation
}

// Where appends a list predicates to the NineBoxEntryDelete builder.
func (_d *NineBoxEntryDelete) Where(ps ...predicate.NineBoxEntry) *NineBoxEntryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NineBoxEntryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NineBoxEntryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NineBoxEntryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(nineboxentry.Table, sqlgraph.NewFieldSpec(nineboxentry.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NineBoxEntryDeleteOne is the builder for deleting a single NineBoxEntry entity.
type NineBoxEntryDeleteOne struct {
	_d *NineBoxEntryDelete
}

// Where appends a list predicates to the NineBoxEntryDelete builder.
func (_d *NineBoxEntryDeleteOne) Where(ps ...predicate.NineBoxEntry) *NineBoxEntryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NineBoxEntryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nineboxentry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NineBoxEntryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
