// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sed-evaluacion-desempeno/api/internal/nineboxscale"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// NineBoxScaleDelete is the builder for deleting a NineBoxScale entity.
type NineBoxScaleDelete struct {
	config
	hooks    []Hook
	mutation *NineBoxScaleMutation
}

// Where appends a list predicates to the NineBoxScaleDelete builder.
func (_d *NineBoxScaleDelete) Where(ps ...predicate.NineBoxScale) *NineBoxScaleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NineBoxScaleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NineBoxScaleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NineBoxScaleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(nineboxscale.Table, sqlgraph.NewFieldSpec(nineboxscale.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NineBoxScaleDeleteOne is the builder for deleting a single NineBoxScale entity.
type NineBoxScaleDeleteOne struct {
	_d *NineBoxScaleDelete
}

// Where appends a list predicates to the NineBoxScaleDelete builder.
func (_d *NineBoxScaleDeleteOne) Where(ps ...predicate.NineBoxScale) *NineBoxScaleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NineBoxScaleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nineboxscale.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NineBoxScaleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
