// Code generated by ent, DO NOT EDIT.

package internal

import (
	"time"

	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/competency"
	"github.com/sed-evaluacion-desempeno/api/internal/competencyacceptancelevel"
	"github.com/sed-evaluacion-desempeno/api/internal/cycle"
	"github.com/sed-evaluacion-desempeno/api/internal/employee"
	"github.com/sed-evaluacion-desempeno/api/internal/evaluationprofile"
	"github.com/sed-evaluacion-desempeno/api/internal/evaluatorscope"
	"github.com/sed-evaluacion-desempeno/api/internal/leveldefinition"
	"github.com/sed-evaluacion-desempeno/api/internal/organization"
	"github.com/sed-evaluacion-desempeno/api/internal/orgnode"
	"github.com/sed-evaluacion-desempeno/api/internal/phasedefinition"
	"github.com/sed-evaluacion-desempeno/api/internal/phasetransition"
	"github.com/sed-evaluacion-desempeno/api/internal/pillar"
	"github.com/sed-evaluacion-desempeno/api/internal/scalecriterion"
	"github.com/sed-evaluacion-desempeno/api/internal/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	competencyMixin := schema.Competency{}.Mixin()
	competencyMixinFields0 := competencyMixin[0].Fields()
	_ = competencyMixinFields0
	competencyFields := schema.Competency{}.Fields()
	_ = competencyFields
	// competencyDescCreatedAt is the schema descriptor for created_at field.
	competencyDescCreatedAt := competencyMixinFields0[0].Descriptor()
	// competency.DefaultCreatedAt holds the default value on creation for the created_at field.
	competency.DefaultCreatedAt = competencyDescCreatedAt.Default.(func() time.Time)
	// competencyDescUpdatedAt is the schema descriptor for updated_at field.
	competencyDescUpdatedAt := competencyMixinFields0[1].Descriptor()
	// competency.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	competency.DefaultUpdatedAt = competencyDescUpdatedAt.Default.(func() time.Time)
	// competency.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	competency.UpdateDefaultUpdatedAt = competencyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// competencyDescName is the schema descriptor for name field.
	competencyDescName := competencyFields[1].Descriptor()
	// competency.NameValidator is a validator for the "name" field. It is called by the builders before save.
	competency.NameValidator = competencyDescName.Validators[0].(func(string) error)
	// competencyDescID is the schema descriptor for id field.
	competencyDescID := competencyFields[0].Descriptor()
	// competency.DefaultID holds the default value on creation for the id field.
	competency.DefaultID = competencyDescID.Default.(func() uuid.UUID)
	competencyacceptancelevelMixin := schema.CompetencyAcceptanceLevel{}.Mixin()
	competencyacceptancelevelMixinFields0 := competencyacceptancelevelMixin[0].Fields()
	_ = competencyacceptancelevelMixinFields0
	competencyacceptancelevelFields := schema.CompetencyAcceptanceLevel{}.Fields()
	_ = competencyacceptancelevelFields
	// competencyacceptancelevelDescCreatedAt is the schema descriptor for created_at field.
	competencyacceptancelevelDescCreatedAt := competencyacceptancelevelMixinFields0[0].Descriptor()
	// competencyacceptancelevel.DefaultCreatedAt holds the default value on creation for the created_at field.
	competencyacceptancelevel.DefaultCreatedAt = competencyacceptancelevelDescCreatedAt.Default.(func() time.Time)
	// competencyacceptancelevelDescUpdatedAt is the schema descriptor for updated_at field.
	competencyacceptancelevelDescUpdatedAt := competencyacceptancelevelMixinFields0[1].Descriptor()
	// competencyacceptancelevel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	competencyacceptancelevel.DefaultUpdatedAt = competencyacceptancelevelDescUpdatedAt.Default.(func() time.Time)
	// competencyacceptancelevel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	competencyacceptancelevel.UpdateDefaultUpdatedAt = competencyacceptancelevelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// competencyacceptancelevelDescLevel is the schema descriptor for level field.
	competencyacceptancelevelDescLevel := competencyacceptancelevelFields[1].Descriptor()
	// competencyacceptancelevel.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	competencyacceptancelevel.LevelValidator = competencyacceptancelevelDescLevel.Validators[0].(func(int) error)
	// competencyacceptancelevelDescID is the schema descriptor for id field.
	competencyacceptancelevelDescID := competencyacceptancelevelFields[0].Descriptor()
	// competencyacceptancelevel.DefaultID holds the default value on creation for the id field.
	competencyacceptancelevel.DefaultID = competencyacceptancelevelDescID.Default.(func() uuid.UUID)
	cycleMixin := schema.Cycle{}.Mixin()
	cycleMixinFields0 := cycleMixin[0].Fields()
	_ = cycleMixinFields0
	cycleFields := schema.Cycle{}.Fields()
	_ = cycleFields
	// cycleDescCreatedAt is the schema descriptor for created_at field.
	cycleDescCreatedAt := cycleMixinFields0[0].Descriptor()
	// cycle.DefaultCreatedAt holds the default value on creation for the created_at field.
	cycle.DefaultCreatedAt = cycleDescCreatedAt.Default.(func() time.Time)
	// cycleDescUpdatedAt is the schema descriptor for updated_at field.
	cycleDescUpdatedAt := cycleMixinFields0[1].Descriptor()
	// cycle.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cycle.DefaultUpdatedAt = cycleDescUpdatedAt.Default.(func() time.Time)
	// cycle.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cycle.UpdateDefaultUpdatedAt = cycleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cycleDescID is the schema descriptor for id field.
	cycleDescID := cycleFields[0].Descriptor()
	// cycle.DefaultID holds the default value on creation for the id field.
	cycle.DefaultID = cycleDescID.Default.(func() uuid.UUID)
	employeeMixin := schema.Employee{}.Mixin()
	employeeMixinFields0 := employeeMixin[0].Fields()
	_ = employeeMixinFields0
	employeeFields := schema.Employee{}.Fields()
	_ = employeeFields
	// employeeDescCreatedAt is the schema descriptor for created_at field.
	employeeDescCreatedAt := employeeMixinFields0[0].Descriptor()
	// employee.DefaultCreatedAt holds the default value on creation for the created_at field.
	employee.DefaultCreatedAt = employeeDescCreatedAt.Default.(func() time.Time)
	// employeeDescUpdatedAt is the schema descriptor for updated_at field.
	employeeDescUpdatedAt := employeeMixinFields0[1].Descriptor()
	// employee.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	employee.DefaultUpdatedAt = employeeDescUpdatedAt.Default.(func() time.Time)
	// employee.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	employee.UpdateDefaultUpdatedAt = employeeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// employeeDescFirstName is the schema descriptor for first_name field.
	employeeDescFirstName := employeeFields[1].Descriptor()
	// employee.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	employee.FirstNameValidator = employeeDescFirstName.Validators[0].(func(string) error)
	// employeeDescLastName is the schema descriptor for last_name field.
	employeeDescLastName := employeeFields[2].Descriptor()
	// employee.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	employee.LastNameValidator = employeeDescLastName.Validators[0].(func(string) error)
	// employeeDescEmployeeNumber is the schema descriptor for employee_number field.
	employeeDescEmployeeNumber := employeeFields[3].Descriptor()
	// employee.EmployeeNumberValidator is a validator for the "employee_number" field. It is called by the builders before save.
	employee.EmployeeNumberValidator = employeeDescEmployeeNumber.Validators[0].(func(string) error)
	// employeeDescEmail is the schema descriptor for email field.
	employeeDescEmail := employeeFields[4].Descriptor()
	// employee.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	employee.EmailValidator = employeeDescEmail.Validators[0].(func(string) error)
	// employeeDescIsActive is the schema descriptor for is_active field.
	employeeDescIsActive := employeeFields[5].Descriptor()
	// employee.DefaultIsActive holds the default value on creation for the is_active field.
	employee.DefaultIsActive = employeeDescIsActive.Default.(bool)
	// employeeDescID is the schema descriptor for id field.
	employeeDescID := employeeFields[0].Descriptor()
	// employee.DefaultID holds the default value on creation for the id field.
	employee.DefaultID = employeeDescID.Default.(func() uuid.UUID)
	evaluationprofileFields := schema.EvaluationProfile{}.Fields()
	_ = evaluationprofileFields
	// evaluationprofileDescName is the schema descriptor for name field.
	evaluationprofileDescName := evaluationprofileFields[1].Descriptor()
	// evaluationprofile.NameValidator is a validator for the "name" field. It is called by the builders before save.
	evaluationprofile.NameValidator = evaluationprofileDescName.Validators[0].(func(string) error)
	// evaluationprofileDescID is the schema descriptor for id field.
	evaluationprofileDescID := evaluationprofileFields[0].Descriptor()
	// evaluationprofile.DefaultID holds the default value on creation for the id field.
	evaluationprofile.DefaultID = evaluationprofileDescID.Default.(func() uuid.UUID)
	evaluatorscopeMixin := schema.EvaluatorScope{}.Mixin()
	evaluatorscopeMixinFields0 := evaluatorscopeMixin[0].Fields()
	_ = evaluatorscopeMixinFields0
	evaluatorscopeFields := schema.EvaluatorScope{}.Fields()
	_ = evaluatorscopeFields
	// evaluatorscopeDescCreatedAt is the schema descriptor for created_at field.
	evaluatorscopeDescCreatedAt := evaluatorscopeMixinFields0[0].Descriptor()
	// evaluatorscope.DefaultCreatedAt holds the default value on creation for the created_at field.
	evaluatorscope.DefaultCreatedAt = evaluatorscopeDescCreatedAt.Default.(func() time.Time)
	// evaluatorscopeDescUpdatedAt is the schema descriptor for updated_at field.
	evaluatorscopeDescUpdatedAt := evaluatorscopeMixinFields0[1].Descriptor()
	// evaluatorscope.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	evaluatorscope.DefaultUpdatedAt = evaluatorscopeDescUpdatedAt.Default.(func() time.Time)
	// evaluatorscope.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	evaluatorscope.UpdateDefaultUpdatedAt = evaluatorscopeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// evaluatorscopeDescID is the schema descriptor for id field.
	evaluatorscopeDescID := evaluatorscopeFields[0].Descriptor()
	// evaluatorscope.DefaultID holds the default value on creation for the id field.
	evaluatorscope.DefaultID = evaluatorscopeDescID.Default.(func() uuid.UUID)
	leveldefinitionFields := schema.LevelDefinition{}.Fields()
	_ = leveldefinitionFields
	// leveldefinitionDescLevel is the schema descriptor for level field.
	leveldefinitionDescLevel := leveldefinitionFields[0].Descriptor()
	// leveldefinition.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	leveldefinition.LevelValidator = leveldefinitionDescLevel.Validators[0].(func(int) error)
	// leveldefinitionDescLabel is the schema descriptor for label field.
	leveldefinitionDescLabel := leveldefinitionFields[1].Descriptor()
	// leveldefinition.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	leveldefinition.LabelValidator = leveldefinitionDescLabel.Validators[0].(func(string) error)
	orgnodeMixin := schema.OrgNode{}.Mixin()
	orgnodeMixinFields0 := orgnodeMixin[0].Fields()
	_ = orgnodeMixinFields0
	orgnodeFields := schema.OrgNode{}.Fields()
	_ = orgnodeFields
	// orgnodeDescCreatedAt is the schema descriptor for created_at field.
	orgnodeDescCreatedAt := orgnodeMixinFields0[0].Descriptor()
	// orgnode.DefaultCreatedAt holds the default value on creation for the created_at field.
	orgnode.DefaultCreatedAt = orgnodeDescCreatedAt.Default.(func() time.Time)
	// orgnodeDescUpdatedAt is the schema descriptor for updated_at field.
	orgnodeDescUpdatedAt := orgnodeMixinFields0[1].Descriptor()
	// orgnode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orgnode.DefaultUpdatedAt = orgnodeDescUpdatedAt.Default.(func() time.Time)
	// orgnode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orgnode.UpdateDefaultUpdatedAt = orgnodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orgnodeDescName is the schema descriptor for name field.
	orgnodeDescName := orgnodeFields[1].Descriptor()
	// orgnode.NameValidator is a validator for the "name" field. It is called by the builders before save.
	orgnode.NameValidator = orgnodeDescName.Validators[0].(func(string) error)
	// orgnodeDescCode is the schema descriptor for code field.
	orgnodeDescCode := orgnodeFields[3].Descriptor()
	// orgnode.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	orgnode.CodeValidator = orgnodeDescCode.Validators[0].(func(string) error)
	// orgnodeDescID is the schema descriptor for id field.
	orgnodeDescID := orgnodeFields[0].Descriptor()
	// orgnode.DefaultID holds the default value on creation for the id field.
	orgnode.DefaultID = orgnodeDescID.Default.(func() uuid.UUID)
	organizationMixin := schema.Organization{}.Mixin()
	organizationMixinFields0 := organizationMixin[0].Fields()
	_ = organizationMixinFields0
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationMixinFields0[0].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationMixinFields0[1].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[1].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescSlug is the schema descriptor for slug field.
	organizationDescSlug := organizationFields[2].Descriptor()
	// organization.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	organization.SlugValidator = organizationDescSlug.Validators[0].(func(string) error)
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationFields[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() uuid.UUID)
	phasedefinitionMixin := schema.PhaseDefinition{}.Mixin()
	phasedefinitionMixinFields0 := phasedefinitionMixin[0].Fields()
	_ = phasedefinitionMixinFields0
	phasedefinitionFields := schema.PhaseDefinition{}.Fields()
	_ = phasedefinitionFields
	// phasedefinitionDescCreatedAt is the schema descriptor for created_at field.
	phasedefinitionDescCreatedAt := phasedefinitionMixinFields0[0].Descriptor()
	// phasedefinition.DefaultCreatedAt holds the default value on creation for the created_at field.
	phasedefinition.DefaultCreatedAt = phasedefinitionDescCreatedAt.Default.(func() time.Time)
	// phasedefinitionDescUpdatedAt is the schema descriptor for updated_at field.
	phasedefinitionDescUpdatedAt := phasedefinitionMixinFields0[1].Descriptor()
	// phasedefinition.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	phasedefinition.DefaultUpdatedAt = phasedefinitionDescUpdatedAt.Default.(func() time.Time)
	// phasedefinition.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	phasedefinition.UpdateDefaultUpdatedAt = phasedefinitionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// phasedefinitionDescLabel is the schema descriptor for label field.
	phasedefinitionDescLabel := phasedefinitionFields[2].Descriptor()
	// phasedefinition.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	phasedefinition.LabelValidator = phasedefinitionDescLabel.Validators[0].(func(string) error)
	// phasedefinitionDescOrder is the schema descriptor for order field.
	phasedefinitionDescOrder := phasedefinitionFields[3].Descriptor()
	// phasedefinition.OrderValidator is a validator for the "order" field. It is called by the builders before save.
	phasedefinition.OrderValidator = phasedefinitionDescOrder.Validators[0].(func(int) error)
	// phasedefinitionDescID is the schema descriptor for id field.
	phasedefinitionDescID := phasedefinitionFields[0].Descriptor()
	// phasedefinition.DefaultID holds the default value on creation for the id field.
	phasedefinition.DefaultID = phasedefinitionDescID.Default.(func() uuid.UUID)
	phasetransitionFields := schema.PhaseTransition{}.Fields()
	_ = phasetransitionFields
	// phasetransitionDescCreatedAt is the schema descriptor for created_at field.
	phasetransitionDescCreatedAt := phasetransitionFields[5].Descriptor()
	// phasetransition.DefaultCreatedAt holds the default value on creation for the created_at field.
	phasetransition.DefaultCreatedAt = phasetransitionDescCreatedAt.Default.(func() time.Time)
	// phasetransitionDescID is the schema descriptor for id field.
	phasetransitionDescID := phasetransitionFields[0].Descriptor()
	// phasetransition.DefaultID holds the default value on creation for the id field.
	phasetransition.DefaultID = phasetransitionDescID.Default.(func() uuid.UUID)
	pillarMixin := schema.Pillar{}.Mixin()
	pillarMixinFields0 := pillarMixin[0].Fields()
	_ = pillarMixinFields0
	pillarFields := schema.Pillar{}.Fields()
	_ = pillarFields
	// pillarDescCreatedAt is the schema descriptor for created_at field.
	pillarDescCreatedAt := pillarMixinFields0[0].Descriptor()
	// pillar.DefaultCreatedAt holds the default value on creation for the created_at field.
	pillar.DefaultCreatedAt = pillarDescCreatedAt.Default.(func() time.Time)
	// pillarDescUpdatedAt is the schema descriptor for updated_at field.
	pillarDescUpdatedAt := pillarMixinFields0[1].Descriptor()
	// pillar.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pillar.DefaultUpdatedAt = pillarDescUpdatedAt.Default.(func() time.Time)
	// pillar.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pillar.UpdateDefaultUpdatedAt = pillarDescUpdatedAt.UpdateDefault.(func() time.Time)
	// pillarDescName is the schema descriptor for name field.
	pillarDescName := pillarFields[1].Descriptor()
	// pillar.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pillar.NameValidator = pillarDescName.Validators[0].(func(string) error)
	// pillarDescID is the schema descriptor for id field.
	pillarDescID := pillarFields[0].Descriptor()
	// pillar.DefaultID holds the default value on creation for the id field.
	pillar.DefaultID = pillarDescID.Default.(func() uuid.UUID)
	scalecriterionMixin := schema.ScaleCriterion{}.Mixin()
	scalecriterionMixinFields0 := scalecriterionMixin[0].Fields()
	_ = scalecriterionMixinFields0
	scalecriterionFields := schema.ScaleCriterion{}.Fields()
	_ = scalecriterionFields
	// scalecriterionDescCreatedAt is the schema descriptor for created_at field.
	scalecriterionDescCreatedAt := scalecriterionMixinFields0[0].Descriptor()
	// scalecriterion.DefaultCreatedAt holds the default value on creation for the created_at field.
	scalecriterion.DefaultCreatedAt = scalecriterionDescCreatedAt.Default.(func() time.Time)
	// scalecriterionDescUpdatedAt is the schema descriptor for updated_at field.
	scalecriterionDescUpdatedAt := scalecriterionMixinFields0[1].Descriptor()
	// scalecriterion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	scalecriterion.DefaultUpdatedAt = scalecriterionDescUpdatedAt.Default.(func() time.Time)
	// scalecriterion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	scalecriterion.UpdateDefaultUpdatedAt = scalecriterionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// scalecriterionDescLevel is the schema descriptor for level field.
	scalecriterionDescLevel := scalecriterionFields[1].Descriptor()
	// scalecriterion.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	scalecriterion.LevelValidator = scalecriterionDescLevel.Validators[0].(func(int) error)
	// scalecriterionDescDescription is the schema descriptor for description field.
	scalecriterionDescDescription := scalecriterionFields[2].Descriptor()
	// scalecriterion.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	scalecriterion.DescriptionValidator = scalecriterionDescDescription.Validators[0].(func(string) error)
	// scalecriterionDescID is the schema descriptor for id field.
	scalecriterionDescID := scalecriterionFields[0].Descriptor()
	// scalecriterion.DefaultID holds the default value on creation for the id field.
	scalecriterion.DefaultID = scalecriterionDescID.Default.(func() uuid.UUID)
}
