// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/cycle"
	"github.com/sed-evaluacion-desempeno/api/internal/orgnode"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
	"github.com/sed-evaluacion-desempeno/api/internal/teamweightconfig"
)

// TeamWeightConfigUpdate is the builder for updating TeamWeightConfig entities.
type TeamWeightConfigUpdate struct {
	config
	hooks    []Hook
	mutation *TeamWeightConfigMutation
}

// Where appends a list predicates to the TeamWeightConfigUpdate builder.
func (_u *TeamWeightConfigUpdate) Where(ps ...predicate.TeamWeightConfig) *TeamWeightConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCycleID sets the "cycle_id" field.
func (_u *TeamWeightConfigUpdate) SetCycleID(v uuid.UUID) *TeamWeightConfigUpdate {
	_u.mutation.SetCycleID(v)
	return _u
}

// SetNillableCycleID sets the "cycle_id" field if the given value is not nil.
func (_u *TeamWeightConfigUpdate) SetNillableCycleID(v *uuid.UUID) *TeamWeightConfigUpdate {
	if v != nil {
		_u.SetCycleID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamWeightConfigUpdate) SetTeamID(v uuid.UUID) *TeamWeightConfigUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamWeightConfigUpdate) SetNillableTeamID(v *uuid.UUID) *TeamWeightConfigUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetJWeight sets the "j_weight" field.
func (_u *TeamWeightConfigUpdate) SetJWeight(v float64) *TeamWeightConfigUpdate {
	_u.mutation.ResetJWeight()
	_u.mutation.SetJWeight(v)
	return _u
}

// SetNillableJWeight sets the "j_weight" field if the given value is not nil.
func (_u *TeamWeightConfigUpdate) SetNillableJWeight(v *float64) *TeamWeightConfigUpdate {
	if v != nil {
		_u.SetJWeight(*v)
	}
	return _u
}

// AddJWeight adds value to the "j_weight" field.
func (_u *TeamWeightConfigUpdate) AddJWeight(v float64) *TeamWeightConfigUpdate {
	_u.mutation.AddJWeight(v)
	return _u
}

// SetPjWeight sets the "pj_weight" field.
func (_u *TeamWeightConfigUpdate) SetPjWeight(v float64) *TeamWeightConfigUpdate {
	_u.mutation.ResetPjWeight()
	_u.mutation.SetPjWeight(v)
	return _u
}

// SetNillablePjWeight sets the "pj_weight" field if the given value is not nil.
func (_u *TeamWeightConfigUpdate) SetNillablePjWeight(v *float64) *TeamWeightConfigUpdate {
	if v != nil {
		_u.SetPjWeight(*v)
	}
	return _u
}

// AddPjWeight adds value to the "pj_weight" field.
func (_u *TeamWeightConfigUpdate) AddPjWeight(v float64) *TeamWeightConfigUpdate {
	_u.mutation.AddPjWeight(v)
	return _u
}

// SetCycle sets the "cycle" edge to the Cycle entity.
func (_u *TeamWeightConfigUpdate) SetCycle(v *Cycle) *TeamWeightConfigUpdate {
	return _u.SetCycleID(v.ID)
}

// SetTeamNodeID sets the "team_node" edge to the OrgNode entity by ID.
func (_u *TeamWeightConfigUpdate) SetTeamNodeID(id uuid.UUID) *TeamWeightConfigUpdate {
	_u.mutation.SetTeamNodeID(id)
	return _u
}

// SetTeamNode sets the "team_node" edge to the OrgNode entity.
func (_u *TeamWeightConfigUpdate) SetTeamNode(v *OrgNode) *TeamWeightConfigUpdate {
	return _u.SetTeamNodeID(v.ID)
}

// Mutation returns the TeamWeightConfigMutation object of the builder.
func (_u *TeamWeightConfigUpdate) Mutation() *TeamWeightConfigMutation {
	return _u.mutation
}

// ClearCycle clears the "cycle" edge to the Cycle entity.
func (_u *TeamWeightConfigUpdate) ClearCycle() *TeamWeightConfigUpdate {
	_u.mutation.ClearCycle()
	return _u
}

// ClearTeamNode clears the "team_node" edge to the OrgNode entity.
func (_u *TeamWeightConfigUpdate) ClearTeamNode() *TeamWeightConfigUpdate {
	_u.mutation.ClearTeamNode()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamWeightConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamWeightConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamWeightConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamWeightConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamWeightConfigUpdate) check() error {
	if v, ok := _u.mutation.JWeight(); ok {
		if err := teamweightconfig.JWeightValidator(v); err != nil {
			return &ValidationError{Name: "j_weight", err: fmt.Errorf(`internal: validator failed for field "TeamWeightConfig.j_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PjWeight(); ok {
		if err := teamweightconfig.PjWeightValidator(v); err != nil {
			return &ValidationError{Name: "pj_weight", err: fmt.Errorf(`internal: validator failed for field "TeamWeightConfig.pj_weight": %w`, err)}
		}
	}
	if _u.mutation.CycleCleared() && len(_u.mutation.CycleIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "TeamWeightConfig.cycle"`)
	}
	if _u.mutation.TeamNodeCleared() && len(_u.mutation.TeamNodeIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "TeamWeightConfig.team_node"`)
	}
	return nil
}

func (_u *TeamWeightConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamweightconfig.Table, teamweightconfig.Columns, sqlgraph.NewFieldSpec(teamweightconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JWeight(); ok {
		_spec.SetField(teamweightconfig.FieldJWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedJWeight(); ok {
		_spec.AddField(teamweightconfig.FieldJWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PjWeight(); ok {
		_spec.SetField(teamweightconfig.FieldPjWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPjWeight(); ok {
		_spec.AddField(teamweightconfig.FieldPjWeight, field.TypeFloat64, value)
	}
	if _u.mutation.CycleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamweightconfig.CycleTable,
			Columns: []string{teamweightconfig.CycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cycle.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CycleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamweightconfig.CycleTable,
			Columns: []string{teamweightconfig.CycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cycle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamNodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamweightconfig.TeamNodeTable,
			Columns: []string{teamweightconfig.TeamNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgnode.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamweightconfig.TeamNodeTable,
			Columns: []string{teamweightconfig.TeamNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgnode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamweightconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamWeightConfigUpdateOne is the builder for updating a single TeamWeightConfig entity.
type TeamWeightConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamWeightConfigMutation
}

// SetCycleID sets the "cycle_id" field.
func (_u *TeamWeightConfigUpdateOne) SetCycleID(v uuid.UUID) *TeamWeightConfigUpdateOne {
	_u.mutation.SetCycleID(v)
	return _u
}

// SetNillableCycleID sets the "cycle_id" field if the given value is not nil.
func (_u *TeamWeightConfigUpdateOne) SetNillableCycleID(v *uuid.UUID) *TeamWeightConfigUpdateOne {
	if v != nil {
		_u.SetCycleID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamWeightConfigUpdateOne) SetTeamID(v uuid.UUID) *TeamWeightConfigUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamWeightConfigUpdateOne) SetNillableTeamID(v *uuid.UUID) *TeamWeightConfigUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetJWeight sets the "j_weight" field.
func (_u *TeamWeightConfigUpdateOne) SetJWeight(v float64) *TeamWeightConfigUpdateOne {
	_u.mutation.ResetJWeight()
	_u.mutation.SetJWeight(v)
	return _u
}

// SetNillableJWeight sets the "j_weight" field if the given value is not nil.
func (_u *TeamWeightConfigUpdateOne) SetNillableJWeight(v *float64) *TeamWeightConfigUpdateOne {
	if v != nil {
		_u.SetJWeight(*v)
	}
	return _u
}

// AddJWeight adds value to the "j_weight" field.
func (_u *TeamWeightConfigUpdateOne) AddJWeight(v float64) *TeamWeightConfigUpdateOne {
	_u.mutation.AddJWeight(v)
	return _u
}

// SetPjWeight sets the "pj_weight" field.
func (_u *TeamWeightConfigUpdateOne) SetPjWeight(v float64) *TeamWeightConfigUpdateOne {
	_u.mutation.ResetPjWeight()
	_u.mutation.SetPjWeight(v)
	return _u
}

// SetNillablePjWeight sets the "pj_weight" field if the given value is not nil.
func (_u *TeamWeightConfigUpdateOne) SetNillablePjWeight(v *float64) *TeamWeightConfigUpdateOne {
	if v != nil {
		_u.SetPjWeight(*v)
	}
	return _u
}

// AddPjWeight adds value to the "pj_weight" field.
func (_u *TeamWeightConfigUpdateOne) AddPjWeight(v float64) *TeamWeightConfigUpdateOne {
	_u.mutation.AddPjWeight(v)
	return _u
}

// SetCycle sets the "cycle" edge to the Cycle entity.
func (_u *TeamWeightConfigUpdateOne) SetCycle(v *Cycle) *TeamWeightConfigUpdateOne {
	return _u.SetCycleID(v.ID)
}

// SetTeamNodeID sets the "team_node" edge to the OrgNode entity by ID.
func (_u *TeamWeightConfigUpdateOne) SetTeamNodeID(id uuid.UUID) *TeamWeightConfigUpdateOne {
	_u.mutation.SetTeamNodeID(id)
	return _u
}

// SetTeamNode sets the "team_node" edge to the OrgNode entity.
func (_u *TeamWeightConfigUpdateOne) SetTeamNode(v *OrgNode) *TeamWeightConfigUpdateOne {
	return _u.SetTeamNodeID(v.ID)
}

// Mutation returns the TeamWeightConfigMutation object of the builder.
func (_u *TeamWeightConfigUpdateOne) Mutation() *TeamWeightConfigMutation {
	return _u.mutation
}

// ClearCycle clears the "cycle" edge to the Cycle entity.
func (_u *TeamWeightConfigUpdateOne) ClearCycle() *TeamWeightConfigUpdateOne {
	_u.mutation.ClearCycle()
	return _u
}

// ClearTeamNode clears the "team_node" edge to the OrgNode entity.
func (_u *TeamWeightConfigUpdateOne) ClearTeamNode() *TeamWeightConfigUpdateOne {
	_u.mutation.ClearTeamNode()
	return _u
}

// Where appends a list predicates to the TeamWeightConfigUpdate builder.
func (_u *TeamWeightConfigUpdateOne) Where(ps ...predicate.TeamWeightConfig) *TeamWeightConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamWeightConfigUpdateOne) Select(field string, fields ...string) *TeamWeightConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamWeightConfig entity.
func (_u *TeamWeightConfigUpdateOne) Save(ctx context.Context) (*TeamWeightConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamWeightConfigUpdateOne) SaveX(ctx context.Context) *TeamWeightConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamWeightConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamWeightConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamWeightConfigUpdateOne) check() error {
	if v, ok := _u.mutation.JWeight(); ok {
		if err := teamweightconfig.JWeightValidator(v); err != nil {
			return &ValidationError{Name: "j_weight", err: fmt.Errorf(`internal: validator failed for field "TeamWeightConfig.j_weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PjWeight(); ok {
		if err := teamweightconfig.PjWeightValidator(v); err != nil {
			return &ValidationError{Name: "pj_weight", err: fmt.Errorf(`internal: validator failed for field "TeamWeightConfig.pj_weight": %w`, err)}
		}
	}
	if _u.mutation.CycleCleared() && len(_u.mutation.CycleIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "TeamWeightConfig.cycle"`)
	}
	if _u.mutation.TeamNodeCleared() && len(_u.mutation.TeamNodeIDs()) > 0 {
		return errors.New(`internal: clearing a required unique edge "TeamWeightConfig.team_node"`)
	}
	return nil
}

func (_u *TeamWeightConfigUpdateOne) sqlSave(ctx context.Context) (_node *TeamWeightConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamweightconfig.Table, teamweightconfig.Columns, sqlgraph.NewFieldSpec(teamweightconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`internal: missing "TeamWeightConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamweightconfig.FieldID)
		for _, f := range fields {
			if !teamweightconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
			}
			if f != teamweightconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JWeight(); ok {
		_spec.SetField(teamweightconfig.FieldJWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedJWeight(); ok {
		_spec.AddField(teamweightconfig.FieldJWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PjWeight(); ok {
		_spec.SetField(teamweightconfig.FieldPjWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPjWeight(); ok {
		_spec.AddField(teamweightconfig.FieldPjWeight, field.TypeFloat64, value)
	}
	if _u.mutation.CycleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamweightconfig.CycleTable,
			Columns: []string{teamweightconfig.CycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cycle.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CycleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamweightconfig.CycleTable,
			Columns: []string{teamweightconfig.CycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cycle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamNodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamweightconfig.TeamNodeTable,
			Columns: []string{teamweightconfig.TeamNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgnode.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamNodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamweightconfig.TeamNodeTable,
			Columns: []string{teamweightconfig.TeamNodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgnode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamWeightConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamweightconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
