// Code generated by ent, DO NOT EDIT.

package teamweightconfig

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldLTE(FieldID, id))
}

// CycleID applies equality check predicate on the "cycle_id" field. It's identical to CycleIDEQ.
func CycleID(v uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldEQ(FieldCycleID, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldEQ(FieldTeamID, v))
}

// JWeight applies equality check predicate on the "j_weight" field. It's identical to JWeightEQ.
func JWeight(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldEQ(FieldJWeight, v))
}

// PjWeight applies equality check predicate on the "pj_weight" field. It's identical to PjWeightEQ.
func PjWeight(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldEQ(FieldPjWeight, v))
}

// CycleIDEQ applies the EQ predicate on the "cycle_id" field.
func CycleIDEQ(v uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldEQ(FieldCycleID, v))
}

// CycleIDNEQ applies the NEQ predicate on the "cycle_id" field.
func CycleIDNEQ(v uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldNEQ(FieldCycleID, v))
}

// CycleIDIn applies the In predicate on the "cycle_id" field.
func CycleIDIn(vs ...uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldIn(FieldCycleID, vs...))
}

// CycleIDNotIn applies the NotIn predicate on the "cycle_id" field.
func CycleIDNotIn(vs ...uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldNotIn(FieldCycleID, vs...))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...uuid.UUID) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldNotIn(FieldTeamID, vs...))
}

// JWeightEQ applies the EQ predicate on the "j_weight" field.
func JWeightEQ(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldEQ(FieldJWeight, v))
}

// JWeightNEQ applies the NEQ predicate on the "j_weight" field.
func JWeightNEQ(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldNEQ(FieldJWeight, v))
}

// JWeightIn applies the In predicate on the "j_weight" field.
func JWeightIn(vs ...float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldIn(FieldJWeight, vs...))
}

// JWeightNotIn applies the NotIn predicate on the "j_weight" field.
func JWeightNotIn(vs ...float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldNotIn(FieldJWeight, vs...))
}

// JWeightGT applies the GT predicate on the "j_weight" field.
func JWeightGT(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldGT(FieldJWeight, v))
}

// JWeightGTE applies the GTE predicate on the "j_weight" field.
func JWeightGTE(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldGTE(FieldJWeight, v))
}

// JWeightLT applies the LT predicate on the "j_weight" field.
func JWeightLT(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldLT(FieldJWeight, v))
}

// JWeightLTE applies the LTE predicate on the "j_weight" field.
func JWeightLTE(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldLTE(FieldJWeight, v))
}

// PjWeightEQ applies the EQ predicate on the "pj_weight" field.
func PjWeightEQ(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldEQ(FieldPjWeight, v))
}

// PjWeightNEQ applies the NEQ predicate on the "pj_weight" field.
func PjWeightNEQ(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldNEQ(FieldPjWeight, v))
}

// PjWeightIn applies the In predicate on the "pj_weight" field.
func PjWeightIn(vs ...float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldIn(FieldPjWeight, vs...))
}

// PjWeightNotIn applies the NotIn predicate on the "pj_weight" field.
func PjWeightNotIn(vs ...float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldNotIn(FieldPjWeight, vs...))
}

// PjWeightGT applies the GT predicate on the "pj_weight" field.
func PjWeightGT(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldGT(FieldPjWeight, v))
}

// PjWeightGTE applies the GTE predicate on the "pj_weight" field.
func PjWeightGTE(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldGTE(FieldPjWeight, v))
}

// PjWeightLT applies the LT predicate on the "pj_weight" field.
func PjWeightLT(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldLT(FieldPjWeight, v))
}

// PjWeightLTE applies the LTE predicate on the "pj_weight" field.
func PjWeightLTE(v float64) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.FieldLTE(FieldPjWeight, v))
}

// HasCycle applies the HasEdge predicate on the "cycle" edge.
func HasCycle() predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CycleTable, CycleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCycleWith applies the HasEdge predicate on the "cycle" edge with a given conditions (other predicates).
func HasCycleWith(preds ...predicate.Cycle) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(func(s *sql.Selector) {
		step := newCycleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamNode applies the HasEdge predicate on the "team_node" edge.
func HasTeamNode() predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamNodeTable, TeamNodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamNodeWith applies the HasEdge predicate on the "team_node" edge with a given conditions (other predicates).
func HasTeamNodeWith(preds ...predicate.OrgNode) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(func(s *sql.Selector) {
		step := newTeamNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamWeightConfig) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamWeightConfig) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamWeightConfig) predicate.TeamWeightConfig {
	return predicate.TeamWeightConfig(sql.NotPredicates(p))
}
