// Code generated by ent, DO NOT EDIT.

package phasedefinition

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the phasedefinition type in the database.
	Label = "phase_definition"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPhase holds the string denoting the phase field in the database.
	FieldPhase = "phase"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// FieldAllowedActors holds the string denoting the allowed_actors field in the database.
	FieldAllowedActors = "allowed_actors"
	// FieldAllowedActions holds the string denoting the allowed_actions field in the database.
	FieldAllowedActions = "allowed_actions"
	// FieldBlockedActions holds the string denoting the blocked_actions field in the database.
	FieldBlockedActions = "blocked_actions"
	// FieldCycleID holds the string denoting the cycle_id field in the database.
	FieldCycleID = "cycle_id"
	// EdgeCycle holds the string denoting the cycle edge name in mutations.
	EdgeCycle = "cycle"
	// EdgeOutgoingTransitions holds the string denoting the outgoing_transitions edge name in mutations.
	EdgeOutgoingTransitions = "outgoing_transitions"
	// EdgeIncomingTransitions holds the string denoting the incoming_transitions edge name in mutations.
	EdgeIncomingTransitions = "incoming_transitions"
	// Table holds the table name of the phasedefinition in the database.
	Table = "phase_definitions"
	// CycleTable is the table that holds the cycle relation/edge.
	CycleTable = "phase_definitions"
	// CycleInverseTable is the table name for the Cycle entity.
	// It exists in this package in order to avoid circular dependency with the "cycle" package.
	CycleInverseTable = "cycles"
	// CycleColumn is the table column denoting the cycle relation/edge.
	CycleColumn = "cycle_id"
	// OutgoingTransitionsTable is the table that holds the outgoing_transitions relation/edge.
	OutgoingTransitionsTable = "phase_transitions"
	// OutgoingTransitionsInverseTable is the table name for the PhaseTransition entity.
	// It exists in this package in order to avoid circular dependency with the "phasetransition" package.
	OutgoingTransitionsInverseTable = "phase_transitions"
	// OutgoingTransitionsColumn is the table column denoting the outgoing_transitions relation/edge.
	OutgoingTransitionsColumn = "from_phase_id"
	// IncomingTransitionsTable is the table that holds the incoming_transitions relation/edge.
	IncomingTransitionsTable = "phase_transitions"
	// IncomingTransitionsInverseTable is the table name for the PhaseTransition entity.
	// It exists in this package in order to avoid circular dependency with the "phasetransition" package.
	IncomingTransitionsInverseTable = "phase_transitions"
	// IncomingTransitionsColumn is the table column denoting the incoming_transitions relation/edge.
	IncomingTransitionsColumn = "to_phase_id"
)

// Columns holds all SQL columns for phasedefinition fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPhase,
	FieldLabel,
	FieldOrder,
	FieldAllowedActors,
	FieldAllowedActions,
	FieldBlockedActions,
	FieldCycleID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// LabelValidator is a validator for the "label" field. It is called by the builders before save.
	LabelValidator func(string) error
	// OrderValidator is a validator for the "order" field. It is called by the builders before save.
	OrderValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Phase defines the type for the "phase" enum field.
type Phase string

// Phase values.
const (
	PhaseAsignacion Phase = "asignacion"
	PhaseAvance     Phase = "avance"
	PhaseCierre     Phase = "cierre"
)

func (ph Phase) String() string {
	return string(ph)
}

// PhaseValidator is a validator for the "phase" field enum values. It is called by the builders before save.
func PhaseValidator(ph Phase) error {
	switch ph {
	case PhaseAsignacion, PhaseAvance, PhaseCierre:
		return nil
	default:
		return fmt.Errorf("phasedefinition: invalid enum value for phase field: %q", ph)
	}
}

// OrderOption defines the ordering options for the PhaseDefinition queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPhase orders the results by the phase field.
func ByPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhase, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByOrder orders the results by the order field.
func ByOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrder, opts...).ToFunc()
}

// ByCycleID orders the results by the cycle_id field.
func ByCycleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCycleID, opts...).ToFunc()
}

// ByCycleField orders the results by cycle field.
func ByCycleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCycleStep(), sql.OrderByField(field, opts...))
	}
}

// ByOutgoingTransitionsCount orders the results by outgoing_transitions count.
func ByOutgoingTransitionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOutgoingTransitionsStep(), opts...)
	}
}

// ByOutgoingTransitions orders the results by outgoing_transitions terms.
func ByOutgoingTransitions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOutgoingTransitionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByIncomingTransitionsCount orders the results by incoming_transitions count.
func ByIncomingTransitionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIncomingTransitionsStep(), opts...)
	}
}

// ByIncomingTransitions orders the results by incoming_transitions terms.
func ByIncomingTransitions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIncomingTransitionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCycleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CycleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CycleTable, CycleColumn),
	)
}
func newOutgoingTransitionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OutgoingTransitionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OutgoingTransitionsTable, OutgoingTransitionsColumn),
	)
}
func newIncomingTransitionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IncomingTransitionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IncomingTransitionsTable, IncomingTransitionsColumn),
	)
}
