// Code generated by ent, DO NOT EDIT.

package goaltemplatekpilink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the goaltemplatekpilink type in the database.
	Label = "goal_template_kpi_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTemplateID holds the string denoting the template_id field in the database.
	FieldTemplateID = "template_id"
	// FieldKpiID holds the string denoting the kpi_id field in the database.
	FieldKpiID = "kpi_id"
	// EdgeTemplate holds the string denoting the template edge name in mutations.
	EdgeTemplate = "template"
	// EdgeKpi holds the string denoting the kpi edge name in mutations.
	EdgeKpi = "kpi"
	// Table holds the table name of the goaltemplatekpilink in the database.
	Table = "goal_template_kpi_links"
	// TemplateTable is the table that holds the template relation/edge.
	TemplateTable = "goal_template_kpi_links"
	// TemplateInverseTable is the table name for the GoalTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "goaltemplate" package.
	TemplateInverseTable = "goal_templates"
	// TemplateColumn is the table column denoting the template relation/edge.
	TemplateColumn = "template_id"
	// KpiTable is the table that holds the kpi relation/edge.
	KpiTable = "goal_template_kpi_links"
	// KpiInverseTable is the table name for the KPI entity.
	// It exists in this package in order to avoid circular dependency with the "kpi" package.
	KpiInverseTable = "kp_is"
	// KpiColumn is the table column denoting the kpi relation/edge.
	KpiColumn = "kpi_id"
)

// Columns holds all SQL columns for goaltemplatekpilink fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTemplateID,
	FieldKpiID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the GoalTemplateKpiLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTemplateID orders the results by the template_id field.
func ByTemplateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateID, opts...).ToFunc()
}

// ByKpiID orders the results by the kpi_id field.
func ByKpiID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKpiID, opts...).ToFunc()
}

// ByTemplateField orders the results by template field.
func ByTemplateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTemplateStep(), sql.OrderByField(field, opts...))
	}
}

// ByKpiField orders the results by kpi field.
func ByKpiField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKpiStep(), sql.OrderByField(field, opts...))
	}
}
func newTemplateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TemplateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TemplateTable, TemplateColumn),
	)
}
func newKpiStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KpiInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, KpiTable, KpiColumn),
	)
}
