// Code generated by ent, DO NOT EDIT.

package phasetransition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sed-evaluacion-desempeno/api/internal/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldCreatedAt, v))
}

// CycleID applies equality check predicate on the "cycle_id" field. It's identical to CycleIDEQ.
func CycleID(v uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldCycleID, v))
}

// FromPhaseID applies equality check predicate on the "from_phase_id" field. It's identical to FromPhaseIDEQ.
func FromPhaseID(v uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldFromPhaseID, v))
}

// ToPhaseID applies equality check predicate on the "to_phase_id" field. It's identical to ToPhaseIDEQ.
func ToPhaseID(v uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldToPhaseID, v))
}

// FromPhaseEQ applies the EQ predicate on the "from_phase" field.
func FromPhaseEQ(v FromPhase) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldFromPhase, v))
}

// FromPhaseNEQ applies the NEQ predicate on the "from_phase" field.
func FromPhaseNEQ(v FromPhase) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldFromPhase, v))
}

// FromPhaseIn applies the In predicate on the "from_phase" field.
func FromPhaseIn(vs ...FromPhase) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldFromPhase, vs...))
}

// FromPhaseNotIn applies the NotIn predicate on the "from_phase" field.
func FromPhaseNotIn(vs ...FromPhase) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldFromPhase, vs...))
}

// ToPhaseEQ applies the EQ predicate on the "to_phase" field.
func ToPhaseEQ(v ToPhase) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldToPhase, v))
}

// ToPhaseNEQ applies the NEQ predicate on the "to_phase" field.
func ToPhaseNEQ(v ToPhase) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldToPhase, v))
}

// ToPhaseIn applies the In predicate on the "to_phase" field.
func ToPhaseIn(vs ...ToPhase) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldToPhase, vs...))
}

// ToPhaseNotIn applies the NotIn predicate on the "to_phase" field.
func ToPhaseNotIn(vs ...ToPhase) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldToPhase, vs...))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v Trigger) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldTrigger, v))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v Trigger) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldTrigger, v))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...Trigger) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldTrigger, vs...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...Trigger) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldTrigger, vs...))
}

// ConditionsIsNil applies the IsNil predicate on the "conditions" field.
func ConditionsIsNil() predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIsNull(FieldConditions))
}

// ConditionsNotNil applies the NotNil predicate on the "conditions" field.
func ConditionsNotNil() predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotNull(FieldConditions))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldLTE(FieldCreatedAt, v))
}

// CycleIDEQ applies the EQ predicate on the "cycle_id" field.
func CycleIDEQ(v uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldCycleID, v))
}

// CycleIDNEQ applies the NEQ predicate on the "cycle_id" field.
func CycleIDNEQ(v uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldCycleID, v))
}

// CycleIDIn applies the In predicate on the "cycle_id" field.
func CycleIDIn(vs ...uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldCycleID, vs...))
}

// CycleIDNotIn applies the NotIn predicate on the "cycle_id" field.
func CycleIDNotIn(vs ...uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldCycleID, vs...))
}

// FromPhaseIDEQ applies the EQ predicate on the "from_phase_id" field.
func FromPhaseIDEQ(v uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldFromPhaseID, v))
}

// FromPhaseIDNEQ applies the NEQ predicate on the "from_phase_id" field.
func FromPhaseIDNEQ(v uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldFromPhaseID, v))
}

// FromPhaseIDIn applies the In predicate on the "from_phase_id" field.
func FromPhaseIDIn(vs ...uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldFromPhaseID, vs...))
}

// FromPhaseIDNotIn applies the NotIn predicate on the "from_phase_id" field.
func FromPhaseIDNotIn(vs ...uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldFromPhaseID, vs...))
}

// ToPhaseIDEQ applies the EQ predicate on the "to_phase_id" field.
func ToPhaseIDEQ(v uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldEQ(FieldToPhaseID, v))
}

// ToPhaseIDNEQ applies the NEQ predicate on the "to_phase_id" field.
func ToPhaseIDNEQ(v uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNEQ(FieldToPhaseID, v))
}

// ToPhaseIDIn applies the In predicate on the "to_phase_id" field.
func ToPhaseIDIn(vs ...uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldIn(FieldToPhaseID, vs...))
}

// ToPhaseIDNotIn applies the NotIn predicate on the "to_phase_id" field.
func ToPhaseIDNotIn(vs ...uuid.UUID) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.FieldNotIn(FieldToPhaseID, vs...))
}

// HasCycle applies the HasEdge predicate on the "cycle" edge.
func HasCycle() predicate.PhaseTransition {
	return predicate.PhaseTransition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CycleTable, CycleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCycleWith applies the HasEdge predicate on the "cycle" edge with a given conditions (other predicates).
func HasCycleWith(preds ...predicate.Cycle) predicate.PhaseTransition {
	return predicate.PhaseTransition(func(s *sql.Selector) {
		step := newCycleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFromPhaseDef applies the HasEdge predicate on the "from_phase_def" edge.
func HasFromPhaseDef() predicate.PhaseTransition {
	return predicate.PhaseTransition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FromPhaseDefTable, FromPhaseDefColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFromPhaseDefWith applies the HasEdge predicate on the "from_phase_def" edge with a given conditions (other predicates).
func HasFromPhaseDefWith(preds ...predicate.PhaseDefinition) predicate.PhaseTransition {
	return predicate.PhaseTransition(func(s *sql.Selector) {
		step := newFromPhaseDefStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasToPhaseDef applies the HasEdge predicate on the "to_phase_def" edge.
func HasToPhaseDef() predicate.PhaseTransition {
	return predicate.PhaseTransition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ToPhaseDefTable, ToPhaseDefColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasToPhaseDefWith applies the HasEdge predicate on the "to_phase_def" edge with a given conditions (other predicates).
func HasToPhaseDefWith(preds ...predicate.PhaseDefinition) predicate.PhaseTransition {
	return predicate.PhaseTransition(func(s *sql.Selector) {
		step := newToPhaseDefStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PhaseTransition) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PhaseTransition) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PhaseTransition) predicate.PhaseTransition {
	return predicate.PhaseTransition(sql.NotPredicates(p))
}
