FROM node:22-alpine
WORKDIR /app

ARG VITE_SHOW_DEV_TOOLBAR=false
ENV VITE_SHOW_DEV_TOOLBAR=$VITE_SHOW_DEV_TOOLBAR

COPY package.json ./
RUN npm install

COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
